# Generated by Django 3.1.6 on 2021-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_crawl',
        ),
        migrations.AddField(
            model_name='user',
            name='is_crawle',
            field=models.BooleanField(null=True, verbose_name='is_crawle'),
        ),
    ]
