# Generated by Django 3.1.6 on 2021-05-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210512_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('ALL_PLAN', '全て対応'), ('URL_PLAN', 'URL指定のみ'), ('WORD_PLAN', '検索ワード指定のみ')], default='ALL_PLAN', max_length=20, verbose_name='プラン'),
        ),
    ]
