# Generated by Django 3.1.6 on 2021-02-12 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsinModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=100, verbose_name='アカウントID')),
                ('asin_group_id', models.CharField(max_length=100, verbose_name='ASINグループID')),
                ('asin', models.CharField(max_length=20, verbose_name='ASIN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 't_asin',
            },
        ),
    ]
