# Generated by Django 3.1.6 on 2021-02-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_asingroupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asingroupmodel',
            name='asin_group_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ASINグループID'),
        ),
    ]
