# Generated by Django 3.1.6 on 2021-02-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20210221_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asingroupmodel',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='asinmodel',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
    ]
