# Generated by Django 3.1.6 on 2021-02-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20210221_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=30, verbose_name='アカウントID')),
                ('yahoo_account_id', models.CharField(default='', max_length=50, verbose_name='ヤフオクアカウントID')),
                ('price_range1', models.IntegerField(default=2000, verbose_name='価格レンジ1')),
                ('price_rate1', models.FloatField(default=1.5, verbose_name='倍率1')),
                ('price_range2', models.IntegerField(default=5000, verbose_name='価格レンジ2')),
                ('price_rate2', models.FloatField(default=1.5, verbose_name='倍率2')),
                ('price_range3', models.IntegerField(default=7000, verbose_name='価格レンジ3')),
                ('price_rate3', models.FloatField(default=1.5, verbose_name='倍率3')),
                ('price_range4', models.IntegerField(default=10000, verbose_name='価格レンジ4')),
                ('price_rate4', models.FloatField(default=1.5, verbose_name='倍率4')),
                ('price_range5', models.IntegerField(default=999999, verbose_name='価格レンジ5')),
                ('price_rate5', models.FloatField(default=1.5, verbose_name='倍率5')),
            ],
        ),
        migrations.AlterField(
            model_name='asinmodel',
            name='account_id',
            field=models.CharField(default='', max_length=100, verbose_name='アカウントID'),
        ),
    ]
