# Generated by Django 3.1.6 on 2021-02-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20210224_2347'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricesettingmodel',
            table='t_price_setting',
        ),
    ]
