# Generated by Django 3.1.6 on 2021-02-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_auto_20210224_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinmodel',
            name='asin_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.asingroupmodel'),
        ),
    ]
