# Generated by Django 3.1.6 on 2021-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_auto_20210225_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='asingroupmodel',
            name='yahoo_account_id',
            field=models.CharField(default='', max_length=100, verbose_name='ヤフーアカウントID'),
        ),
    ]
