# Generated by Django 3.1.6 on 2021-03-01 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_auto_20210226_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionAsins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=30, verbose_name='アカウントID')),
                ('asin', models.CharField(max_length=10, verbose_name='除外ASIN')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='登録日')),
            ],
            options={
                'db_table': 't_exclude_asin',
            },
        ),
        migrations.CreateModel(
            name='ExclusionWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=30, verbose_name='アカウントID')),
                ('word', models.CharField(max_length=100, verbose_name='除外ワード')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='登録日')),
            ],
            options={
                'db_table': 't_exclude_word',
            },
        ),
    ]
