# Generated by Django 3.1.6 on 2021-03-02 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_auto_20210302_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusionword',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='exclusionword',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日'),
        ),
    ]
