# Generated by Django 2.2.5 on 2021-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_auto_20210302_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, verbose_name='アカウントID')),
                ('yahoo_account_id', models.CharField(max_length=100, verbose_name='ヤフーアカウントID')),
                ('eval_message', models.CharField(max_length=256, verbose_name='評価メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 't_eval_message',
            },
        ),
    ]
