# Generated by Django 2.2.5 on 2021-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_syuppincommonsettingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asingroupmodel',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='取得開始日時'),
        ),
    ]
