# Generated by Django 3.1.6 on 2021-03-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_asingroupmodel_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syuppincommonsettingmodel',
            name='account_id',
            field=models.CharField(choices=[], default='', max_length=100, verbose_name='アカウントID'),
        ),
    ]
