# Generated by Django 3.1.6 on 2021-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_auto_20210309_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asingroupmodel',
            name='asin_group_id',
            field=models.CharField(max_length=100, verbose_name='ASINグループID'),
        ),
    ]
