# Generated by Django 3.1.6 on 2021-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_auto_20210319_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='syuppin_sleep_sec',
            field=models.IntegerField(default=5, verbose_name='出品毎の待ち時間(秒)'),
        ),
    ]
