# Generated by Django 3.1.6 on 2021-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0020_syuppincommonsettingmodel_syuppin_sleep_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='auction_mode',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='auto_extention',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='auto_saisyuppin',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='bad_hyouka_seigen',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='description_template',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='fast_end',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='hyouka_seigen',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='item_condition',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='kaisai_kikan',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='nyuusatsusya_ninsyou_seigen',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='other_shipping_method',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='other_shipping_price',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='shipping_date',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='souryou_futan',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='syuppin_sleep_sec',
        ),
        migrations.RemoveField(
            model_name='syuppincommonsettingmodel',
            name='units',
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='assembly_time',
            field=models.IntegerField(default=0, max_length=10, verbose_name='組み立て時間'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='assembly_time_unit_of_measure',
            field=models.CharField(choices=[('years', 'years'), ('秒', '秒'), ('months', 'months'), ('days', 'days'), ('時間', '時間'), ('weeks', 'weeks'), ('分', '分')], default='', max_length=10, verbose_name='組み立て時間の単位 - [ hobbies ]'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='batteries_required',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=5, verbose_name='この商品は電池本体ですか？または電池を使用した商品ですか？'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='battery_cell_composition',
            field=models.CharField(choices=[('グラスマット吸収式鉛酸 (AGM)', 'グラスマット吸収式鉛酸 (AGM)'), ('リチウム空気', 'リチウム空気'), ('コバルト酸リチウム', 'コバルト酸リチウム'), ('リチウムニッケルコバルトアルミニウム(NCA)', 'リチウムニッケルコバルトアルミニウム(NCA)'), ('ニッケルマンガンコバルト酸リチウム', 'ニッケルマンガンコバルト酸リチウム'), ('リン酸リチウム', 'リン酸リチウム'), ('チタン酸リチウム', 'チタン酸リチウム'), ('ニッケル鉄', 'ニッケル鉄'), ('ニッケル・亜鉛電池', 'ニッケル・亜鉛電池'), ('銀カルシウム', '銀カルシウム'), ('銀亜鉛', '銀亜鉛'), ('空気亜鉛', '空気亜鉛'), ('塩化チオニルリチウム', '塩化チオニルリチウム'), ('オキシ水酸化ニッケル', 'オキシ水酸化ニッケル'), ('塩化亜鉛', '塩化亜鉛'), ('リチウム', 'リチウム'), ('亜鉛炭素', '亜鉛炭素'), ('酸化水銀', '酸化水銀'), ('密閉型鉛蓄', '密閉型鉛蓄'), ('NiMh', 'NiMh'), ('アルカリ', 'アルカリ'), ('リチウムポリマー', 'リチウムポリマー'), ('ニッケルカドミウム', 'ニッケルカドミウム'), ('酸化銀', '酸化銀'), ('リチウム二酸化マンガン', 'リチウム二酸化マンガン'), ('鉛カルシウム', '鉛カルシウム'), ('リチウム金属', 'リチウム金属'), ('ポリマー', 'ポリマー'), ('アルミニウム酸素', 'アルミニウム酸素'), ('鉛酸蓄', '鉛酸蓄'), ('亜鉛', '亜鉛'), ('マンガン', 'マンガン'), ('リチウムイオン', 'リチウムイオン')], default='', max_length=20, verbose_name='電池の組成'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='battery_description',
            field=models.CharField(default='', max_length=32, verbose_name='電池の説明'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='battery_type1',
            field=models.CharField(choices=[('AA', 'AA'), ('AAA', 'AAA'), ('リチウムイオン', 'リチウムイオン'), ('battery_type_a', 'battery_type_a'), ('CR2', 'CR2'), ('C', 'C'), ('D', 'D'), ('CR5', 'CR5'), ('battery_type_aaaa', 'battery_type_aaaa'), ('battery_type_p76', 'battery_type_p76'), ('battery_type_product_specific', 'battery_type_product_specific'), ('battery_type_lithium_metal', 'battery_type_lithium_metal'), ('CR123A', 'CR123A'), ('battery_type_12v', 'battery_type_12v'), ('9V', '9V')], default='', max_length=20, verbose_name='電池付属'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='battery_type2',
            field=models.CharField(choices=[('AA', 'AA'), ('AAA', 'AAA'), ('リチウムイオン', 'リチウムイオン'), ('battery_type_a', 'battery_type_a'), ('CR2', 'CR2'), ('C', 'C'), ('D', 'D'), ('CR5', 'CR5'), ('battery_type_aaaa', 'battery_type_aaaa'), ('battery_type_p76', 'battery_type_p76'), ('battery_type_product_specific', 'battery_type_product_specific'), ('battery_type_lithium_metal', 'battery_type_lithium_metal'), ('CR123A', 'CR123A'), ('battery_type_12v', 'battery_type_12v'), ('9V', '9V')], default='', max_length=20, verbose_name='電池付属'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='battery_type3',
            field=models.CharField(choices=[('AA', 'AA'), ('AAA', 'AAA'), ('リチウムイオン', 'リチウムイオン'), ('battery_type_a', 'battery_type_a'), ('CR2', 'CR2'), ('C', 'C'), ('D', 'D'), ('CR5', 'CR5'), ('battery_type_aaaa', 'battery_type_aaaa'), ('battery_type_p76', 'battery_type_p76'), ('battery_type_product_specific', 'battery_type_product_specific'), ('battery_type_lithium_metal', 'battery_type_lithium_metal'), ('CR123A', 'CR123A'), ('battery_type_12v', 'battery_type_12v'), ('9V', '9V')], default='', max_length=20, verbose_name='電池付属'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='battery_weight',
            field=models.IntegerField(default=0, max_length=10, verbose_name='電池の重量(グラム)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='battery_weight_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=20, verbose_name='電池の重量の測定単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='brand_name',
            field=models.CharField(default='', max_length=50, verbose_name='ブランド名（日本語16字）'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='bullet_point1',
            field=models.CharField(default='', max_length=166, verbose_name='商品の仕様'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='bullet_point2',
            field=models.CharField(default='', max_length=166, verbose_name='商品の仕様'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='bullet_point3',
            field=models.CharField(default='', max_length=166, verbose_name='商品の仕様'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='bullet_point4',
            field=models.CharField(default='', max_length=166, verbose_name='商品の仕様'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='bullet_point5',
            field=models.CharField(default='', max_length=166, verbose_name='商品の仕様'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='business_price',
            field=models.IntegerField(default=0, max_length=18, verbose_name='法人価格'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='care_instructions1',
            field=models.CharField(default='', max_length=166, verbose_name='お取り扱い上の注意'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='care_instructions2',
            field=models.CharField(default='', max_length=166, verbose_name='お取り扱い上の注意'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='care_instructions3',
            field=models.CharField(default='', max_length=166, verbose_name='お取り扱い上の注意'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='catalog_number',
            field=models.CharField(default='', max_length=40, verbose_name='出品者カタログ番号'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='collection_name',
            field=models.CharField(default='', max_length=32, verbose_name='コレクション名'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='color_map',
            field=models.CharField(choices=[('イエロー', 'イエロー'), ('オレンジ', 'オレンジ'), ('クリーム', 'クリーム'), ('グリーン', 'グリーン'), ('グレー', 'グレー'), ('ゴールド', 'ゴールド'), ('シルバー', 'シルバー'), ('パープル', 'パープル'), ('ピンク', 'ピンク'), ('ブラウン', 'ブラウン'), ('ブラック', 'ブラック'), ('ブルー', 'ブルー'), ('ブロンズ', 'ブロンズ'), ('ベージュ', 'ベージュ'), ('ホワイト', 'ホワイト'), ('マルチカラー', 'マルチカラー'), ('レッド', 'レッド'), ('水色', '水色'), ('透明', '透明'), ('黄緑', '黄緑')], default='', max_length=20, verbose_name='カラーマップ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='color_name',
            field=models.CharField(default='', max_length=50, verbose_name='カラー'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='condition_note',
            field=models.CharField(default='', max_length=333, verbose_name='商品のコンディション説明'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='condition_type',
            field=models.CharField(choices=[('コレクター商品 - ほぼ新品', 'コレクター商品 - ほぼ新品'), ('コレクター商品 - 非常に良い', 'コレクター商品 - 非常に良い'), ('コレクター商品 - 良い', 'コレクター商品 - 良い'), ('コレクター商品 -可', 'コレクター商品 - 可'), ('中古 - ほぼ新品', '中古 - ほぼ新品'), ('中古 - 非常に良い', '中古 - 非常に良い'), ('中古 - 良い', '中古 - 良い'), ('中古 - 可', '中古 - 可'), ('新品', '新品')], default='未使用', max_length=30, verbose_name='商品のコンディション'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='controller_type',
            field=models.CharField(choices=[('押しボタン', '押しボタン'), ('タッチ', 'タッチ'), ('fully_automatic', 'fully_automatic'), ('jog_dial', 'jog_dial'), ('mechanical_knob', 'mechanical_knob'), ('semi_automatic', 'semi_automatic'), ('Nest', 'Nest'), ('Wireless Gateway Wayne Dalton Gateway', 'Wireless Gateway Wayne Dalton Gateway'), ('XGIOOO Controller', 'XGIOOO Controller'), ('zControl Home Adapter', 'zControl Home Adapter'), ('Netgear Home Automation & Control Unit', 'Netgear Home Automation & Control Unit'), ('NetLinx ZigBee Gateway', 'NetLinx ZigBee Gateway'), ('Mi Casa Verde Vera 3', 'Mi Casa Verde Vera 3'), ('デジタル', 'デジタル'), ('機械系', '機械系'), ('その他', 'その他'), ('Nucleus GE', 'Nucleus GE'), ('Leviton Lumina', 'Leviton Lumina'), ('OpenHome Coverage', 'OpenHome Coverage'), ('iControl iHub', 'iControl iHub'), ('BaseCamp', 'BaseCamp'), ('Mi Casa Verde Vera 2', 'Mi Casa Verde Vera 2'), ('GE Nucleus', 'GE Nucleus'), ('Cisco Linkys', 'Cisco Linkys'), ('ActiveHome', 'ActiveHome'), ('iControl Open Home Connect Platform', 'iControl Open Home Connect Platform'), ('Vivint', 'Vivint'), ('Insteon Hub', 'Insteon Hub'), ('Almond', 'Almond'), ('ZCS101', 'ZCS101'), ('Mi Casa Verde  VeraLite', 'Mi Casa Verde  VeraLite'), ('Honeywell Tuxedo Touch', 'Honeywell Tuxedo Touch'), ('SmartThings', 'SmartThings'), ('Honeywell Z Bridge', 'Honeywell Z Bridge'), ('EZSrve', 'EZSrve'), ('Control4', 'Control4'), ('IR Pro Insteon', 'IR Pro Insteon'), ('Iris', 'Iris'), ('Skylink', 'Skylink'), ('Amazon Echo', 'Amazon Echo'), ('Go Control', 'Go Control'), ('Somfy', 'Somfy'), ('Schlage LiNK Bridge', 'Schlage LiNK Bridge'), ('Motorola CPx100', 'Motorola CPx100'), ('OpenHome Connect', 'OpenHome Connect'), ('Web Mountain RUC 01K', 'Web Mountain RUC 01K'), ('TaHomA', 'TaHomA'), ('Nexia', 'Nexia'), ('hand_control', 'hand_control'), ('voice_control', 'voice_control'), ('foot_control', 'foot_control'), ('remote_control', 'remote_control'), ('remote_control', 'remote_control'), ('motorolo_cpx100', 'motorolo_cpx100'), ('xzcontrol_home_adapter', 'xzcontrol_home_adapter'), ('wireless_garteway_wayne_dalton_gateway', 'wireless_garteway_wayne_dalton_gateway'), ('google_assistant', 'google_assistant'), ('homekit', 'homekit'), ('ifttt', 'ifttt'), ('ring', 'ring'), ('vera', 'vera'), ('wemo', 'wemo'), ('wink', 'wink')], default='', max_length=20, verbose_name='コントローラタイプ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='country_of_origin',
            field=models.CharField(default='', max_length=50, verbose_name='原産国/地域'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='country_string',
            field=models.CharField(choices=[('アイスランド', 'アイスランド'), ('アイルランド', 'アイルランド'), ('アゼルバイジャン', 'アゼルバイジャン'), ('アフガニスタン', 'アフガニスタン'), ('アメリカ合衆国', 'アメリカ合衆国'), ('アメリカ領サモア', 'アメリカ領サモア'), ('アメリカ領ヴァージン諸島', 'アメリカ領ヴァージン諸島'), ('アラブ首長国連邦', 'アラブ首長国連邦'), ('アルジェリア', 'アルジェリア'), ('アルゼンチン', 'アルゼンチン'), ('アルバ', 'アルバ'), ('アルバニア', 'アルバニア'), ('アルメニア', 'アルメニア'), ('アンギラ', 'アンギラ'), ('アンゴラ', 'アンゴラ'), ('アンティグア・バーブーダ', 'アンティグア・バーブーダ'), ('アンドラ', 'アンドラ'), ('イエメン', 'イエメン'), ('イギリス', 'イギリス'), ('イギリス領インド洋地域', 'イギリス領インド洋地域'), ('イギリス領ヴァージン諸島', 'イギリス領ヴァージン諸島'), ('イスラエル', 'イスラエル'), ('イタリア', 'イタリア'), ('イラク', 'イラク'), ('イラン', 'イラン'), ('インド', 'インド'), ('インドネシア', 'インドネシア'), ('ウォリス・フツナ', 'ウォリス・フツナ'), ('ウガンダ', 'ウガンダ'), ('ウクライナ', 'ウクライナ'), ('ウズベキスタン', 'ウズベキスタン'), ('ウルグアイ', 'ウルグアイ'), ('エクアドル', 'エクアドル'), ('エジプト', 'エジプト'), ('エストニア', 'エストニア'), ('エチオピア', 'エチオピア'), ('エリトリア', 'エリトリア'), ('エルサルバドル', 'エルサルバドル'), ('オマーン', 'オマーン'), ('オランダ', 'オランダ'), ('オランダ領アンティル', 'オランダ領アンティル'), ('オーストラリア', 'オーストラリア'), ('オーストリア', 'オーストリア'), ('オーランド諸島', 'オーランド諸島'), ('カザフスタン', 'カザフスタン'), ('カタール', 'カタール'), ('カナダ', 'カナダ'), ('カメルーン', 'カメルーン'), ('カンボジア', 'カンボジア'), ('カーボベルデ', 'カーボベルデ'), ('ガイアナ', 'ガイアナ'), ('ガボン', 'ガボン'), ('ガンビア', 'ガンビア'), ('ガーナ', 'ガーナ'), ('ガーンジー', 'ガーンジー'), ('キプロス', 'キプロス'), ('キューバ', 'キューバ'), ('キリバス', 'キリバス'), ('キルギス', 'キルギス'), ('ギニア', 'ギニア'), ('ギニアビサウ', 'ギニアビサウ'), ('ギリシャ', 'ギリシャ'), ('クウェート', 'クウェート'), ('クック諸島', 'クック諸島'), ('クリスマス島', 'クリスマス島'), ('クロアチア', 'クロアチア'), ('グアテマラ', 'グアテマラ'), ('グアドループ', 'グアドループ'), ('グアム', 'グアム'), ('グリーンランド', 'グリーンランド'), ('グルジア', 'グルジア'), ('グレナダ', 'グレナダ'), ('ケイマン諸島', 'ケイマン諸島'), ('ケニア', 'ケニア'), ('ココス諸島', 'ココス諸島'), ('コスタリカ', 'コスタリカ'), ('コモロ', 'コモロ'), ('コロンビア', 'コロンビア'), ('コンゴ共和国', 'コンゴ共和国'), ('コンゴ民主共和国', 'コンゴ民主共和国'), ('コートジボワール', 'コートジボワール'), ('サウジアラビア', 'サウジアラビア'), ('サウスジョージア・サウスサンドウィッチ諸島', 'サウスジョージア・サウスサンドウィッチ諸島'), ('サモア', 'サモア'), ('サントメ・プリンシペ', 'サントメ・プリンシペ'), ('サンピエール島・ミクロン島', 'サンピエール島・ミクロン島'), ('サンマリノ', 'サンマリノ'), ('サン・バルテルミー島', 'サン・バルテルミー島'), ('サン・マルタン島', 'サン・マルタン島'), ('ザンビア', 'ザンビア'), ('シエラレオネ', 'シエラレオネ'), ('シリア', 'シリア'), ('シンガポール', 'シンガポール'), ('ジブチ', 'ジブチ'), ('ジブラルタル', 'ジブラルタル'), ('ジャマイカ', 'ジャマイカ'), ('ジャージー', 'ジャージー'), ('ジンバブエ', 'ジンバブエ'), ('スイス', 'スイス'), ('スウェーデン', 'スウェーデン'), ('スペイン', 'スペイン'), ('スリナム', 'スリナム'), ('スリランカ', 'スリランカ'), ('スロバキア', 'スロバキア'), ('スロベニア', 'スロベニア'), ('スワジランド', 'スワジランド'), ('スヴァールバル諸島およびヤンマイエン島', 'スヴァールバル諸島およびヤンマイエン島'), ('スーダン', 'スーダン'), ('セネガル', 'セネガル'), ('セルビア', 'セルビア'), ('セントクリストファー・ネイビス', 'セントクリストファー・ネイビス'), ('セントビンセント・グレナディーン', 'セントビンセント・グレナディーン'), ('セントヘレナ・アセンションおよびトリスタン・ダ・クーニャ', 'セントヘレナ・アセンションおよびトリスタン・ダ・クーニャ'), ('セントルシア', 'セントルシア'), ('セーシェル', 'セーシェル'), ('ソマリア', 'ソマリア'), ('ソロモン諸島', 'ソロモン諸島'), ('タイ', 'タイ'), ('タジキスタン', 'タジキスタン'), ('タンザニア', 'タンザニア'), ('タークス・カイコス諸島', 'タークス・カイコス諸島'), ('チェコ', 'チェコ'), ('チャド', 'チャド'), ('チュニジア', 'チュニジア'), ('チリ', 'チリ'), ('ツバル', 'ツバル'), ('デンマーク', 'デンマーク'), ('トケラウ', 'トケラウ'), ('トリニダード・トバゴ', 'トリニダード・トバゴ'), ('トルクメニスタン', 'トルクメニスタン'), ('トルコ', 'トルコ'), ('トンガ', 'トンガ'), ('トーゴ', 'トーゴ'), ('ドイツ', 'ドイツ'), ('ドミニカ共和国', 'ドミニカ共和国'), ('ドミニカ国', 'ドミニカ国'), ('ナイジェリア', 'ナイジェリア'), ('ナウル', 'ナウル'), ('ナミビア', 'ナミビア'), ('ニウエ', 'ニウエ'), ('ニカラグア', 'ニカラグア'), ('ニジェール', 'ニジェール'), ('ニューカレドニア', 'ニューカレドニア'), ('ニュージーランド', 'ニュージーランド'), ('ネパール', 'ネパール'), ('ノルウェー', 'ノルウェー'), ('ノーフォーク島', 'ノーフォーク島'), ('ハイチ', 'ハイチ'), ('ハンガリー', 'ハンガリー'), ('ハード島とマクドナルド諸島', 'ハード島とマクドナルド諸島'), ('バチカン', 'バチカン'), ('バヌアツ', 'バヌアツ'), ('バハマ', 'バハマ'), ('バミューダ諸島', 'バミューダ諸島'), ('バルバドス', 'バルバドス'), ('バングラデシュ', 'バングラデシュ'), ('バーレーン', 'バーレーン'), ('パキスタン', 'パキスタン'), ('パナマ', 'パナマ'), ('パプアニューギニア', 'パプアニューギニア'), ('パラオ', 'パラオ'), ('パラグアイ', 'パラグアイ'), ('パレスチナ', 'パレスチナ'), ('ピトケアン', 'ピトケアン'), ('フィジー', 'フィジー'), ('フィリピン', 'フィリピン'), ('フィンランド', 'フィンランド'), ('フェロー諸島', 'フェロー諸島'), ('フォークランド諸島', 'フォークランド諸島'), ('フランス', 'フランス'), ('フランス領ギアナ', 'フランス領ギアナ'), ('フランス領ポリネシア', 'フランス領ポリネシア'), ('フランス領南方・南極地域', 'フランス領南方・南極地域'), ('ブラジル', 'ブラジル'), ('ブルガリア', 'ブルガリア'), ('ブルキナファソ', 'ブルキナファソ'), ('ブルネイ', 'ブルネイ'), ('ブルンジ', 'ブルンジ'), ('ブータン', 'ブータン'), ('ブーベ島', 'ブーベ島'), ('プエルトリコ', 'プエルトリコ'), ('ベトナム', 'ベトナム'), ('ベナン', 'ベナン'), ('ベネズエラ', 'ベネズエラ'), ('ベラルーシ', 'ベラルーシ'), ('ベリーズ', 'ベリーズ'), ('ベルギー', 'ベルギー'), ('ペルー', 'ペルー'), ('ホンジュラス', 'ホンジュラス'), ('ボスニア・ヘルツェゴビナ', 'ボスニア・ヘルツェゴビナ'), ('ボツワナ', 'ボツワナ'), ('ボリビア', 'ボリビア'), ('ポルトガル', 'ポルトガル'), ('ポーランド', 'ポーランド'), ('マカオ', 'マカオ'), ('マケドニア共和国', 'マケドニア共和国'), ('マダガスカル', 'マダガスカル'), ('マヨット', 'マヨット'), ('マラウイ', 'マラウイ'), ('マリ', 'マリ'), ('マルタ', 'マルタ'), ('マルティニーク', 'マルティニーク'), ('マレーシア', 'マレーシア'), ('マン島', 'マン島'), ('マーシャル諸島', 'マーシャル諸島'), ('ミクロネシア連邦', 'ミクロネシア連邦'), ('ミャンマー', 'ミャンマー'), ('メキシコ', 'メキシコ'), ('モザンビーク', 'モザンビーク'), ('モナコ', 'モナコ'), ('モルディブ', 'モルディブ'), ('モルドバ', 'モルドバ'), ('モロッコ', 'モロッコ'), ('モンゴル', 'モンゴル'), ('モンテネグロ', 'モンテネグロ'), ('モントセラト', 'モントセラト'), ('モーリシャス', 'モーリシャス'), ('モーリタニア', 'モーリタニア'), ('ヨルダン', 'ヨルダン'), ('ラオス', 'ラオス'), ('ラトビア', 'ラトビア'), ('リトアニア', 'リトアニア'), ('リヒテンシュタイン', 'リヒテンシュタイン'), ('リビア', 'リビア'), ('リベリア', 'リベリア'), ('ルクセンブルク', 'ルクセンブルク'), ('ルワンダ', 'ルワンダ'), ('ルーマニア', 'ルーマニア'), ('レソト', 'レソト'), ('レバノン', 'レバノン'), ('レユニオン', 'レユニオン'), ('ロシア', 'ロシア'), ('中央アフリカ', '中央アフリカ'), ('中華人民共和国', '中華人民共和国'), ('北マリアナ諸島', '北マリアナ諸島'), ('南アフリカ', '南アフリカ'), ('南極', '南極'), ('台湾(台湾省/中華民国)', '台湾(台湾省/中華民国)'), ('合衆国領有小離島', '合衆国領有小離島'), ('大韓民国', '大韓民国'), ('日本', '日本'), ('朝鮮民主主義人民共和国', '朝鮮民主主義人民共和国'), ('東ティモール', '東ティモール'), ('西サハラ', '西サハラ'), ('赤道ギニア', '赤道ギニア'), ('香港', '香港')], default='', max_length=50, verbose_name='製造国/地域'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='delivery_schedule_group_id',
            field=models.CharField(default='', max_length=50, verbose_name='配送日時指定SKUリスト'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='distribution_designation',
            field=models.CharField(choices=[('JP Parallel Import', 'JP Parallel Import')], default='', max_length=10, verbose_name='販売形態(並行輸入品)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='edition',
            field=models.CharField(default='', max_length=20, verbose_name='版'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='educational_objective',
            field=models.CharField(default='', max_length=166, verbose_name='教育目標'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='engine_type',
            field=models.CharField(choices=[('ハイブリッド', 'ハイブリッド'), ('燃料', '燃料'), ('蒸気', '蒸気'), ('電気', '電気')], default='', max_length=10, verbose_name='エンジンタイプ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='external_product_id',
            field=models.CharField(default='', max_length=16, verbose_name='商品コード(JANコード)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='external_product_id_type',
            field=models.CharField(default='', max_length=16, verbose_name='商品コードのタイプ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='feed_product_type',
            field=models.CharField(choices=[('ToysAndGames', 'ToysAndGames'), ('Hobbies', 'hobbies'), ('BabyProducts', 'BabyProducts')], default='', max_length=30, verbose_name='商品タイプ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='flash_point',
            field=models.IntegerField(default=0, max_length=10, verbose_name='引火点(°C)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='folded_size',
            field=models.CharField(default='', max_length=166, verbose_name='折りたたみ時のサイズ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='frequency_bands_supported',
            field=models.CharField(default='', max_length=166, verbose_name='サポート周波数帯域'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='fulfillment_center_id',
            field=models.CharField(choices=[('AMAZON_JP', 'AMAZON_JP'), ('DEFAULT', 'DEFAULT')], default='', max_length=10, verbose_name='フルフィルメントセンターID'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='fulfillment_latency',
            field=models.IntegerField(default=0, max_length=10, verbose_name='出荷作業日数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='generic_keywords',
            field=models.CharField(default='', max_length=50, verbose_name='検索キーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='genre',
            field=models.CharField(default='', max_length=50, verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='ghs_classification_class1',
            field=models.CharField(choices=[('爆発物', '爆発物'), ('可燃性', '可燃性'), ('酸化性', '酸化性'), ('高圧ガス', '高圧ガス'), ('腐食性', '腐食性'), ('毒性', '毒性'), ('刺激性', '刺激性'), ('健康有害性', '健康有害性'), ('環境有害性', '環境有害性'), ('ラベル表示なし', 'ラベル表示なし')], default='', max_length=20, verbose_name='商品の容量の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='ghs_classification_class2',
            field=models.CharField(choices=[('爆発物', '爆発物'), ('可燃性', '可燃性'), ('酸化性', '酸化性'), ('高圧ガス', '高圧ガス'), ('腐食性', '腐食性'), ('毒性', '毒性'), ('刺激性', '刺激性'), ('健康有害性', '健康有害性'), ('環境有害性', '環境有害性'), ('ラベル表示なし', 'ラベル表示なし')], default='', max_length=20, verbose_name='商品の容量の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='ghs_classification_class3',
            field=models.CharField(choices=[('爆発物', '爆発物'), ('可燃性', '可燃性'), ('酸化性', '酸化性'), ('高圧ガス', '高圧ガス'), ('腐食性', '腐食性'), ('毒性', '毒性'), ('刺激性', '刺激性'), ('健康有害性', '健康有害性'), ('環境有害性', '環境有害性'), ('ラベル表示なし', 'ラベル表示なし')], default='', max_length=20, verbose_name='商品の容量の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='handle_height',
            field=models.FloatField(default=0, max_length=10, verbose_name='ハンドルの高さ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='handle_height_unit_of_measure',
            field=models.CharField(choices=[('オングストローム', 'オングストローム'), ('ミル', 'ミル'), ('ヤード', 'ヤード'), ('ピコメートル', 'ピコメートル'), ('マイル', 'マイル'), ('DM', 'DM'), ('MM', 'MM'), ('M', 'M'), ('IN', 'IN'), ('FT', 'FT'), ('CM', 'CM'), ('100分の1インチ', '100分の1インチ'), ('ナノメートル', 'ナノメートル'), ('µM', 'µM'), ('キロメートル', 'キロメートル')], default='', max_length=10, verbose_name='ハンドルの高さの単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='hazmat_united_nations_regulatory_id',
            field=models.CharField(default='', max_length=50, verbose_name='国連(UN)番号'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='is_adult_product',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=10, verbose_name='アダルト商品'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='is_assembly_required',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='', max_length=10, verbose_name='要組み立て'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='is_discontinued_by_manufacturer',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=10, verbose_name='メーカー製造中止'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='is_expiration_dated_product',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='', max_length=10, verbose_name='賞味期限管理商品'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_dimensions_unit_of_measure',
            field=models.CharField(choices=[('オングストローム', 'オングストローム'), ('ミル', 'ミル'), ('ヤード', 'ヤード'), ('ピコメートル', 'ピコメートル'), ('マイル', 'マイル'), ('DM', 'DM'), ('MM', 'MM'), ('M', 'M'), ('IN', 'IN'), ('FT', 'FT'), ('CM', 'CM'), ('100分の1インチ', '100分の1インチ'), ('ナノメートル', 'ナノメートル'), ('µM', 'µM'), ('キロメートル', 'キロメートル')], default='', max_length=10, verbose_name='商品の寸法の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_display_length',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品の長さ（パッケージを含まない）(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_display_length_unit_of_measure',
            field=models.CharField(choices=[('オングストローム', 'オングストローム'), ('ミル', 'ミル'), ('ヤード', 'ヤード'), ('ピコメートル', 'ピコメートル'), ('マイル', 'マイル'), ('DM', 'DM'), ('MM', 'MM'), ('M', 'M'), ('IN', 'IN'), ('FT', 'FT'), ('CM', 'CM'), ('100分の1インチ', '100分の1インチ'), ('ナノメートル', 'ナノメートル'), ('µM', 'µM'), ('キロメートル', 'キロメートル')], default='', max_length=10, verbose_name='商品の長さの単位(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_display_weight',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品の重量（パッケージを含まない）(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_display_weight_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=10, verbose_name='商品の重量の単位(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_height',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品の高さ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_length',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品の長さ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_name',
            field=models.CharField(default='', max_length=50, verbose_name='商品名'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_package_quantity',
            field=models.IntegerField(default=0, max_length=10, verbose_name='パッケージ商品数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_sku',
            field=models.CharField(default='', max_length=30, verbose_name='出品者SKU'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_volume',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品の体積'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_volume_unit_of_measure',
            field=models.CharField(choices=[('cup', 'cup'), ('microliters', 'microliters'), ('cubic-F', 'cubic-F'), ('centiliters', 'centiliters'), ('gallon', 'gallon'), ('quart', 'quart'), ('nanoliters', 'nanoliters'), ('liter', 'liter'), ('picoliters', 'picoliters'), ('Unknown modifier', 'Unknown modifier'), ('fluid_ounces', 'fluid_ounces'), ('cubic-m', 'cubic-m'), ('pint', 'pint'), ('cubic_yards', 'cubic_yards'), ('cubic-in', 'cubic-in'), ('imperial_gallons', 'imperial_gallons'), ('milliliter', 'milliliter'), ('cubic-cm', 'cubic-cm'), ('deciliters', 'deciliters')], default='', max_length=20, verbose_name='商品の容量の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_weight',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品の重量'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_weight_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=20, verbose_name='商品の重量の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='item_width',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品の幅'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='language_value',
            field=models.CharField(choices=[('ドイツ語', 'ドイツ語'), ('aragonese', 'aragonese'), ('sidamo', 'sidamo'), ('altaic_languages', 'altaic_languages'), ('luo', 'luo'), ('khotanese', 'khotanese'), ('Kinyarwanda', 'Kinyarwanda'), ('papuan_languages', 'papuan_languages'), ('Hausa', 'Hausa'), ('elamite', 'elamite'), ('Dutch', 'Dutch'), ('old_french', 'old_french'), ('classical_syriac', 'classical_syriac'), ('Flemish', 'Flemish'), ('kokborok', 'kokborok'), ('Nepali', 'Nepali'), ('songhao_languages', 'songhao_languages'), ('makasar', 'makasar'), ('ancient_greek', 'antient_greek'), ('sardinian', 'sardinian'), ('chinook_jargon', 'chinool_jargon'), ('niger_kordofanian_languages', 'niger_kordofanian_languages'), ('Cayuga', 'Cayuga'), ('Castilian', 'Castilian'), ('old_irish', 'okd_irish'), ('Persian', 'Persian'), ('aleut', 'aleut'), ('jula', 'jula'), ('siksika', 'siksika'), ('pohnpeian', 'pohnpeian'), ('mzima', 'nzima'), ('chiricahua', 'chiricahua'), ('Slswati', 'Slswati'), ('Sumerian', 'Sumerian'), ('north_american_indian_languages', 'north_american_indian_languages'), ('minangkabau', 'minangkabau'), ('dravidian_languages', 'dravidian_languages'), ('gorontalo', 'gorontalo'), ('Slovak', 'Slovak'), ('Hebrew', 'Hebrew'), ('sasak', 'sasak'), ('ekajuk', 'ekajuk'), ('northern_sami', 'northern_sami'), ('chechen', 'chechen'), ('selkup', 'selkup'), ('Kirundi', 'Kirundi'), ('braj', 'braj'), ('ベンガル語', 'ベンガル語'), ('celtic_languages', 'celtic_languages'), ('Azerbaijani', 'Azerbaijani'), ('sorbian_languages', 'sorbian_languages'), ('upper_sorbian', 'upper_sorbian'), ('scots', 'scots'), ('Afrikaans', 'Afrikaans'), ('sami', 'sami'), ('umbundu', 'umbundu'), ('australian_languages', 'australian_languages'), ('assyrian', 'assyrian'), ('Navaho', 'Navaho'), ('khoisan_languages', 'khoisan_languages'), ('Lithuanian', 'Lithuanian'), ('Bambara', 'Bambara'), ('chamic_languages', 'chamic_languages'), ('ベトナム語', 'ベトナム語'), ('bini', 'bini'), ('Maltese', 'Maltnese')], default='', max_length=20, verbose_name='対応言語'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='legal_disclaimer_description',
            field=models.CharField(default='', max_length=333, verbose_name='法規上の免責条項'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='list_price',
            field=models.IntegerField(default=0, max_length=10, verbose_name='メーカー希望価格'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='lithium_battery_energy_content',
            field=models.IntegerField(default=0, max_length=10, verbose_name='電池当たりのワット時'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='lithium_battery_energy_content_unit_of_measure',
            field=models.CharField(choices=[('キロワット時', 'キロワット時'), ('ジュール', 'ジュール'), ('立方フィート', '立方フィート'), ('ワット時', 'ワット時'), ('ミリアンペア時', 'ミリアンペア時'), ('立方メートル', '立方メートル'), ('ミリアンペア時間', 'ミリアンペア時間'), ('ミリアンペア秒', 'ミリアンペア秒'), ('英熱量', '英熱量')], default='', max_length=20, verbose_name='リチウム電池のエネルギー量測定単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='lithium_battery_packaging',
            field=models.CharField(choices=[('時計と別に梱包', '時計と別に梱包'), ('時計本体にセット済み', '時計本体にセット済み'), ('電池のみ', '電池のみ')], default='', max_length=20, verbose_name='リチウム電池パッケージ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='lithium_battery_voltage',
            field=models.CharField(default='', max_length=10, verbose_name='リチウム電池エネルギー含有量'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='lithium_battery_voltage_unit_of_measure',
            field=models.CharField(choices=[('Volts (AC)', 'Volts (AC)'), ('Volts (DC)', 'Volts (DC)'), ('Kilovolts', 'Kilovolts'), ('Nanovolts', 'Nanovolts'), ('Microvolts', 'Microvolts'), ('ボルト', 'ボルト'), ('Millivolts', 'Millivolts')], default='', max_length=10, verbose_name='リチウム電池の電圧の測定単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='lithium_battery_weight',
            field=models.IntegerField(default=0, max_length=10, verbose_name='リチウム含有量(グラム)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='lithium_battery_weight_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=20, verbose_name='リチウム電池の重量の測定単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='main_image_url',
            field=models.CharField(default='', max_length=500, verbose_name='商品メイン画像URL'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='manufacturer',
            field=models.CharField(default='', max_length=50, verbose_name='メーカー名(日本語１６字)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='material_composition',
            field=models.CharField(default='', max_length=333, verbose_name='素材構成'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='material_type',
            field=models.CharField(choices=[('ABS', 'ABS'), ('ATBC-PVC', 'ATBC-PVC'), ('POM', 'POM'), ('PP', 'PP'), ('PVC', 'PVC'), ('TPE', 'TPE'), ('アクリル', 'アクリル'), ('アルミニウム', 'アルミニウム'), ('カーボン', 'カーボン'), ('ガラス', 'ガラス'), ('コールドキャスト', 'コールドキャスト'), ('シルク', 'シルク'), ('スウェード', 'スウェード'), ('スチール', 'スチール'), ('セラミック', 'セラミック'), ('ソフトビニール', 'ソフトビニール'), ('ダンボール', 'ダンボール'), ('ツイード', 'ツイード'), ('ナイロン', 'ナイロン'), ('ビニール', 'ビニール'), ('ファイバー', 'ファイバー'), ('プラスチック', 'プラスチック'), ('ベルボア', 'ベルボア'), ('ポリエステル', 'ポリエステル'), ('ポリエチレン', 'ポリエチレンン'), ('ポリストーン', 'ポリストーン'), ('ポリプロピレン', 'ポリプロピレン'), ('マイクロファイバー', 'マイクロファイバー'), ('ラテックス', 'ラテックス'), ('レジン', 'レジン'), ('レーヨン', 'レーヨン'), ('合皮', '合皮'), ('合金', '合金'), ('塩化ビニール', '塩化ビニール'), ('天然皮', '天然皮'), ('天然皮', '天然皮'), ('木', '木'), ('真鍮', '真鍮'), ('紙', '紙'), ('綿', '綿'), ('金属', '金属')], default='', max_length=20, verbose_name='素材の種類'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='max_order_quantity',
            field=models.IntegerField(default=0, max_length=5, verbose_name='最大注文個数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='maximum_height_recommendation',
            field=models.FloatField(default=0, max_length=20, verbose_name='メーカー推奨最大身長(日本で使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='maximum_height_recommendation_unit_of_measure',
            field=models.CharField(choices=[('オングストローム', 'オングストローム'), ('ミル', 'ミル'), ('ヤード', 'ヤード'), ('ピコメートル', 'ピコメートル'), ('マイル', 'マイル'), ('DM', 'DM'), ('MM', 'MM'), ('M', 'M'), ('IN', 'IN'), ('FT', 'FT'), ('CM', 'CM'), ('100分の1インチ', '100分の1インチ'), ('ナノメートル', 'ナノメートル'), ('µM', 'µM'), ('キロメートル', 'キロメートル')], default='', max_length=10, verbose_name='推奨最高身長の単位(日本で使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='maximum_weight_recommendation',
            field=models.FloatField(default=0, max_length=20, verbose_name='メーカー推奨最大重量(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='maximum_weight_recommendation_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=10, verbose_name='メーカー推奨最大体重の単位(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='merchant_release_date',
            field=models.DateField(null=True, verbose_name='予約商品の販売開始日'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='merchant_shipping_group_name',
            field=models.CharField(choices=[('移行された配送パターン', '移行された配送パターン')], default='', max_length=10, verbose_name='配送パターン'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='mfg_maximum',
            field=models.IntegerField(default=0, max_length=20, verbose_name='メーカー推奨最高年齢'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='mfg_maximum_unit_of_measure',
            field=models.CharField(choices=[('months', 'months'), ('years', 'years')], default='', max_length=10, verbose_name='メーカー推奨最少年齢の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='mfg_minimum',
            field=models.IntegerField(default=0, max_length=20, verbose_name='メーカー推奨最少年齢'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='mfg_minimum_unit_of_measure',
            field=models.CharField(choices=[('months', 'months'), ('years', 'years')], default='', max_length=10, verbose_name='メーカー推奨最少年齢の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='minimum_height_recommendation',
            field=models.FloatField(default=0, max_length=20, verbose_name='メーカー推奨最低身長(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='minimum_height_recommendation_unit_of_measure',
            field=models.CharField(choices=[('オングストローム', 'オングストローム'), ('ミル', 'ミル'), ('ヤード', 'ヤード'), ('ピコメートル', 'ピコメートル'), ('マイル', 'マイル'), ('DM', 'DM'), ('MM', 'MM'), ('M', 'M'), ('IN', 'IN'), ('FT', 'FT'), ('CM', 'CM'), ('100分の1インチ', '100分の1インチ'), ('ナノメートル', 'ナノメートル'), ('µM', 'µM'), ('キロメートル', 'キロメートル')], default='', max_length=10, verbose_name='推奨最低身長の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='minimum_weight_recommendation',
            field=models.FloatField(default=0, max_length=20, verbose_name='メーカー推奨最低重量(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='minimum_weight_recommendation_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=10, verbose_name='メーカー推奨最少体重の単位(日本では使用不可)'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='model',
            field=models.CharField(default='NON', max_length=50, verbose_name='型番'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='number_of_batteries1',
            field=models.IntegerField(default=0, max_length=10, verbose_name='電池の数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='number_of_batteries2',
            field=models.IntegerField(default=0, max_length=10, verbose_name='電池の数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='number_of_batteries3',
            field=models.IntegerField(default=0, max_length=10, verbose_name='電池の数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='number_of_items',
            field=models.IntegerField(default=0, max_length=10, verbose_name='付属品総数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='number_of_lithium_ion_cells',
            field=models.IntegerField(default=0, max_length=10, verbose_name='リチウムイオン電池単数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='number_of_lithium_metal_cells',
            field=models.IntegerField(default=0, max_length=10, verbose_name='リチウムメタル電池単数'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='number_of_pieces',
            field=models.IntegerField(default=0, max_length=10, verbose_name='商品の個数（ピース数）'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='offering_can_be_gift_messaged',
            field=models.CharField(default='', max_length=50, verbose_name='ギフトメッセージ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='offering_can_be_giftwrapped',
            field=models.CharField(default='', max_length=50, verbose_name='ギフト包装'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='offering_end_date',
            field=models.DateField(null=True, verbose_name='セール終了日'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='offering_start_date',
            field=models.DateField(null=True, verbose_name='販売開始日'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='optional_payment_type_exclusion',
            field=models.CharField(choices=[('exclude cvs', 'exclude cvs'), ('exclude cod, cvs', 'exclude cod, cvs'), ('exclude_none', 'exclude_none'), ('exclude cod', 'exclude cod')], default='', max_length=20, verbose_name='使用しない支払い方法'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url1',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL1'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url2',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL2'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url3',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL3'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url4',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL4'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url5',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL5'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url6',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL6'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url7',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL7'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='other_image_url8',
            field=models.CharField(default='', max_length=500, verbose_name='商品サブ画像URL8'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='package_dimensions_unit_of_measure',
            field=models.CharField(choices=[('オングストローム', 'オングストローム'), ('ミル', 'ミル'), ('ヤード', 'ヤード'), ('ピコメートル', 'ピコメートル'), ('マイル', 'マイル'), ('DM', 'DM'), ('MM', 'MM'), ('M', 'M'), ('IN', 'IN'), ('FT', 'FT'), ('CM', 'CM'), ('100分の1インチ', '100分の1インチ'), ('ナノメートル', 'ナノメートル'), ('µM', 'µM'), ('キロメートル', 'キロメートル')], default='', max_length=10, verbose_name='商品パッケージの寸法の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='package_height',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品パッケージの高さ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='package_length',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品パッケージの長さ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='package_weight',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品パッケージの重量'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='package_weight_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=10, verbose_name='商品パッケージの重量の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='package_width',
            field=models.FloatField(default=0, max_length=10, verbose_name='商品パッケージの幅'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='parent_child',
            field=models.CharField(choices=[('parent', 'parent'), ('child', 'child')], default='', max_length=10, verbose_name='親子関係の指定'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='parent_sku',
            field=models.CharField(default='', max_length=40, verbose_name='親商品のSKU（商品管理番号）'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='part_number',
            field=models.CharField(default='NON', max_length=40, verbose_name='メーカ型番'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='platinum_keywords1',
            field=models.CharField(default='', max_length=50, verbose_name='プラチナキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='platinum_keywords2',
            field=models.CharField(default='', max_length=50, verbose_name='プラチナキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='platinum_keywords3',
            field=models.CharField(default='', max_length=50, verbose_name='プラチナキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='platinum_keywords4',
            field=models.CharField(default='', max_length=50, verbose_name='プラチナキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='platinum_keywords5',
            field=models.CharField(default='', max_length=50, verbose_name='プラチナキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='pricing_action',
            field=models.CharField(choices=[('delete business_price', 'delete business_price'), ('delete quantity_price', 'delete quantity_price'), ('delete progressive_discount', 'delete progressive_discount')], default='', max_length=10, verbose_name='価格設定操作'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='product_description',
            field=models.CharField(default='', max_length=666, verbose_name='商品説明'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='product_site_launch_date',
            field=models.DateField(null=True, verbose_name='商品の公開日'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='product_tax_code',
            field=models.CharField(choices=[('A_GEN_NOTAX', 'A_GEN_NOTAX'), ('A_GEN_STANDARD', 'A_GEN_STANDARD'), ('A_GEN_REDUCED', 'A_GEN_REDUCED')], default='', max_length=10, verbose_name='商品タックスコード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='progressive_discount_lower_bound1',
            field=models.IntegerField(default=0, max_length=18, verbose_name='累積購入割引の下限値1'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='progressive_discount_lower_bound2',
            field=models.IntegerField(default=0, max_length=18, verbose_name='累積購入割引の下限値2'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='progressive_discount_lower_bound3',
            field=models.IntegerField(default=0, max_length=18, verbose_name='累積購入割引の下限値3'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='progressive_discount_type',
            field=models.CharField(choices=[('fixed', 'fixed'), ('percent', 'percent')], default='', max_length=10, verbose_name='累積購入割引のタイプ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='progressive_discount_value1',
            field=models.IntegerField(default=0, max_length=18, verbose_name='累積購入割引価格1'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='progressive_discount_value2',
            field=models.IntegerField(default=0, max_length=18, verbose_name='累積購入割引価格2'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='progressive_discount_value3',
            field=models.IntegerField(default=0, max_length=18, verbose_name='累積購入割引価格3'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_lower_bound1',
            field=models.IntegerField(default=0, max_length=18, verbose_name='数量の下限1'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_lower_bound2',
            field=models.IntegerField(default=0, max_length=18, verbose_name='数量の下限2'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_lower_bound3',
            field=models.IntegerField(default=0, max_length=18, verbose_name='数量の下限3'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_lower_bound4',
            field=models.IntegerField(default=0, max_length=18, verbose_name='数量の下限4'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_lower_bound5',
            field=models.IntegerField(default=0, max_length=18, verbose_name='数量の下限5'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_price1',
            field=models.CharField(default='', max_length=10, verbose_name='数量割引1'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_price2',
            field=models.CharField(default='', max_length=10, verbose_name='数量割引2'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_price3',
            field=models.CharField(default='', max_length=10, verbose_name='数量割引3'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_price4',
            field=models.CharField(default='', max_length=10, verbose_name='数量割引4'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_price5',
            field=models.CharField(default='', max_length=10, verbose_name='数量割引5'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='quantity_price_type',
            field=models.CharField(choices=[('fixed', 'fixed'), ('percent', 'percent')], default='', max_length=10, verbose_name='数量割引のタイプ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='rail_gauge',
            field=models.CharField(choices=[('16番', '16番'), ('1番', '1番'), ('2番', '2番'), ('3番', '3番'), ('G', 'G'), ('HO', 'HO'), ('N', 'N'), ('O', 'v'), ('O(0番)', 'O(0番)'), ('OO', 'OO'), ('S', 'S'), ('TT', 'TT'), ('Z', 'Z')], default='', max_length=10, verbose_name='レールの規格'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='recommended_browse_nodes',
            field=models.CharField(choices=[('Explore', 'Explore'), ('Edge', 'Edge'), ('safari', 'safari'), ('chrome', 'chrome')], default='', max_length=30, verbose_name='推奨ブラウズノード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='recommended_uses_for_product',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='', max_length=10, verbose_name='推奨使用用途'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='relationship_type',
            field=models.CharField(default='Variation', max_length=10, verbose_name='親子関係のタイプ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='remote_control_technology',
            field=models.CharField(choices=[('有線', '有線'), ('無線', '無線')], default='', max_length=10, verbose_name='有線or無線'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='restock_date',
            field=models.DateField(null=True, verbose_name='商品の入荷予定日'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='safety_data_sheet_url',
            field=models.CharField(default='', max_length=300, verbose_name='安全データシート(SDS) URL'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='safety_warning',
            field=models.CharField(default='', max_length=500, verbose_name='安全性の注意点'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='sale_end_date',
            field=models.DateField(null=True, verbose_name='セール終了日'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='sale_from_date',
            field=models.DateField(null=True, verbose_name='セール開始日'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='sale_price',
            field=models.IntegerField(default=0, max_length=18, verbose_name='セール価格'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='sale_price_points',
            field=models.IntegerField(default=0, max_length=10, verbose_name='セール時ポイント'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='scale_name',
            field=models.CharField(choices=[('1/1', '1/1'), ('1/10', '1/10'), ('1/100', '1/100'), ('1/1000', '1/1000'), ('1/10000', '1/10000'), ('1/108', '1/108'), ('1/11', '1/11'), ('1/12', '1/12'), ('1/120', '1/120'), ('1/1200', '1/1200'), ('1/121.92', '1/121.92'), ('1/1250', '1/1250'), ('1/128', '1/128'), ('1/1400', '1/1400'), ('1/144', '1/144'), ('1/15', '1/15'), ('1/150', '1/150'), ('1/1500', '1/1500'), ('1/152', '1/152'), ('1/16', '1/16'), ('1/160', '1/160'), ('1/18', '1/18'), ('1/182.88', '1/182.88'), ('1/19', '1/19'), ('1/2', '1/2'), ('1/2.5', '1/2.5'), ('1/20', '1/20'), ('1/200', '1/200'), ('1/2000', '1/2000'), ('1/20000', '1/20000'), ('1/22.5', '1/22.5'), ('1/220', '1/220'), ('1/24', '1/24'), ('1/2400', '1/2400'), ('1/25', '1/25'), ('1/250', '1/250'), ('1/2500', '1/2500'), ('1/28', '1/28'), ('1/285', '1/285'), ('1/288', '1/288'), ('1/29', '1/29'), ('1/3', '1/3'), ('1/30', '1/30'), ('1/30.5', '1/30.5'), ('1/300', '1/300'), ('1/3000', '1/3000'), ('1/302', '1/302'), ('1/32', '1/32'), ('1/33', '1/33'), ('1/34', '1/34'), ('1/35', '1/35'), ('1/350', '1/350'), ('1/36', '1/36'), ('1/3900', '1/3900'), ('1/4', '1/4'), ('1/40', '1/40'), ('1/400', '1/400'), ('1/4105', '1/4105'), ('1/43', '1/43'), ('1/43.5', '1/43.5'), ('1/432', '1/432'), ('1/45', '1/45'), ('1/450', '1/450'), ('1/48', '1/48'), ('1/4800', '1/4800'), ('1/5', '1/5'), ('1/5.5', '1/5.5'), ('1/50', '1/50'), ('1/500', '1/500'), ('1/55', '1/55'), ('1/572', '1/572'), ('1/6', '1/6'), ('1/60', '1/60'), ('1/60.96', '1/60.96'), ('1/600', '1/600'), ('1/650', '1/650'), ('1/7', '1/7'), ('1/700', '1/700'), ('1/72', '1/72'), ('1/720', '1/720'), ('1/73.152', '1/73.152'), ('1/75', '1/75'), ('1/76', '1/76'), ('1/76.2', '1/76.2'), ('1/8', '1/8'), ('1/8000', '1/8000'), ('1/82', '1/82'), ('1/87', '1/87'), ('1/87.1', '1/87.1'), ('1/90', '1/90'), ('1/900', '1/900'), ('1/91.44', '1/91.44'), ('1/96', '1/96')], default='', max_length=10, verbose_name='スケール名'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='seat_width',
            field=models.FloatField(default=0, max_length=10, verbose_name='シートの幅'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='seat_width_unit_of_measure',
            field=models.CharField(choices=[('オングストローム', 'オングストローム'), ('ミル', 'ミル'), ('ヤード', 'ヤード'), ('ピコメートル', 'ピコメートル'), ('マイル', 'マイル'), ('DM', 'DM'), ('MM', 'MM'), ('M', 'M'), ('IN', 'IN'), ('FT', 'FT'), ('CM', 'CM'), ('100分の1インチ', '100分の1インチ'), ('ナノメートル', 'ナノメートル'), ('µM', 'µM'), ('キロメートル', 'キロメートル')], default='', max_length=10, verbose_name='座面（椅子）の幅の単位'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='shaft_style_type',
            field=models.CharField(default='', max_length=50, verbose_name='shaft_style_type'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='size_map',
            field=models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small'), ('X-Large', 'X-Large'), ('X-Small', 'X-Small'), ('XX-Large', 'XX-Large'), ('XX-Small', 'XX-Small'), ('XXX-Large', 'XXX-Large'), ('XXX-Small', 'XXX-Small'), ('XXXX-Large', 'XXXX-Large'), ('XXXX-Small', 'XXXX-Small'), ('XXXXX-Large', 'XXXXX-Large'), ('XXXXX-Small', 'XXXXX-Small')], default='', max_length=10, verbose_name='サイズマップ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='size_name',
            field=models.CharField(default='', max_length=50, verbose_name='サイズ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='special_features1',
            field=models.CharField(default='', max_length=166, verbose_name='機能性'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='special_features2',
            field=models.CharField(default='', max_length=166, verbose_name='機能性'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='special_features3',
            field=models.CharField(default='', max_length=166, verbose_name='機能性'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='special_features4',
            field=models.CharField(default='', max_length=166, verbose_name='機能性'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='special_features5',
            field=models.CharField(default='', max_length=166, verbose_name='機能性'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='specific_uses_for_product',
            field=models.CharField(default='', max_length=50, verbose_name='特徴・用途'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='standard_price',
            field=models.IntegerField(default=0, max_length=18, verbose_name='商品の販売価格'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='standard_price_points',
            field=models.IntegerField(default=0, max_length=10, verbose_name='セール価格'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='style_name',
            field=models.CharField(default='', max_length=50, verbose_name='スタイル名'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='subject_character',
            field=models.CharField(default='', max_length=50, verbose_name='キャラクター'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='supplier_declared_dg_hz_regulation1',
            field=models.CharField(choices=[('GHSシンボル', 'GHSシンボル'), ('不明', '不明'), ('その他', 'その他'), ('該当なし', '該当なし'), ('輸送', '輸送'), ('廃棄', '廃棄'), ('保管 ', '保管 ')], default='', max_length=20, verbose_name='適用される危険物関連法令'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='supplier_declared_dg_hz_regulation2',
            field=models.CharField(choices=[('GHSシンボル', 'GHSシンボル'), ('不明', '不明'), ('その他', 'その他'), ('該当なし', '該当なし'), ('輸送', '輸送'), ('廃棄', '廃棄'), ('保管 ', '保管 ')], default='', max_length=20, verbose_name='適用される危険物関連法令'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='supplier_declared_dg_hz_regulation3',
            field=models.CharField(choices=[('GHSシンボル', 'GHSシンボル'), ('不明', '不明'), ('その他', 'その他'), ('該当なし', '該当なし'), ('輸送', '輸送'), ('廃棄', '廃棄'), ('保管 ', '保管 ')], default='', max_length=20, verbose_name='適用される危険物関連法令'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='supplier_declared_dg_hz_regulation4',
            field=models.CharField(choices=[('GHSシンボル', 'GHSシンボル'), ('不明', '不明'), ('その他', 'その他'), ('該当なし', '該当なし'), ('輸送', '輸送'), ('廃棄', '廃棄'), ('保管 ', '保管 ')], default='', max_length=20, verbose_name='適用される危険物関連法令'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='supplier_declared_dg_hz_regulation5',
            field=models.CharField(choices=[('GHSシンボル', 'GHSシンボル'), ('不明', '不明'), ('その他', 'その他'), ('該当なし', '該当なし'), ('輸送', '輸送'), ('廃棄', '廃棄'), ('保管 ', '保管 ')], default='', max_length=20, verbose_name='適用される危険物関連法令'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='swatch_image_url',
            field=models.CharField(default='', max_length=500, verbose_name='カラーサンプル画像'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='target_audience_keywords1',
            field=models.CharField(default='', max_length=50, verbose_name='ターゲットユーザーのキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='target_audience_keywords2',
            field=models.CharField(default='', max_length=50, verbose_name='ターゲットユーザーのキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='target_audience_keywords3',
            field=models.CharField(default='', max_length=50, verbose_name='ターゲットユーザーのキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='target_audience_keywords4',
            field=models.CharField(default='', max_length=50, verbose_name='ターゲットユーザーのキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='target_audience_keywords5',
            field=models.CharField(default='', max_length=50, verbose_name='ターゲットユーザーのキーワード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='target_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unisex', 'unisex')], default='', max_length=10, verbose_name='対象性別'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='update_delete',
            field=models.CharField(choices=[('Update', 'Update'), ('PartialUpdate', 'PartialUpdate'), ('Delete', 'Delete')], default='', max_length=30, verbose_name='推奨ブラウズノード'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='variation_theme',
            field=models.CharField(choices=[('Size', 'Size'), ('Color', 'Color'), ('colorsize', 'colorsize'), ('edition', 'edition'), ('stylename', 'stylename'), ('SizeName', 'SizeName'), ('SizeName-ColorName', 'SizeName-ColorName')], default='', max_length=50, verbose_name='バリエーションテーマ'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='warranty_description',
            field=models.CharField(default='', max_length=500, verbose_name='メーカー保証の説明'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='website_shipping_weight',
            field=models.FloatField(default=0, max_length=20, verbose_name='配送重量'),
        ),
        migrations.AddField(
            model_name='syuppincommonsettingmodel',
            name='website_shipping_weight_unit_of_measure',
            field=models.CharField(choices=[('LB', 'LB'), ('KG', 'KG'), ('GR', 'GR'), ('100分の1ポンド', '100分の1ポンド'), ('MG', 'MG'), ('トン', 'トン'), ('OZ', 'OZ')], default='', max_length=20, verbose_name='発送重量の単位'),
        ),
    ]
