# Generated by Django 3.1.6 on 2021-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0020_syuppincommonsettingmodel_syuppin_sleep_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchUrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=32, verbose_name='アカウントID')),
                ('url', models.TextField(max_length=64, verbose_name='URL')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 't_fetch_url',
            },
        ),
    ]
