# Generated by Django 3.1.6 on 2021-04-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0022_searchwordmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistWordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=32, verbose_name='アカウントID')),
                ('blacklist_word', models.TextField(max_length=16, verbose_name='NGワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 't_blacklist_word',
            },
        ),
    ]
