# Generated by Django 3.1.6 on 2021-04-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0024_blacklistsellermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=32, verbose_name='アカウントID')),
                ('seq_no', models.IntegerField(verbose_name='シーケンス番号')),
                ('base_price', models.IntegerField(default=0, verbose_name='価格レンジ')),
                ('profit', models.IntegerField(default=0, verbose_name='利益額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 't_profit',
            },
        ),
    ]
