# Generated by Django 3.1.6 on 2021-04-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0025_profitmodel'),
        ('setting', '0021_auto_20210413_1213'),
    ]

    operations = [
    ]
