# Generated by Django 3.1.6 on 2021-04-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0026_merge_20210415_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyuppinCommonSettingModel',
        ),
    ]
