# Generated by Django 3.1.6 on 2021-04-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0027_delete_syuppincommonsettingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistsellermodel',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='blacklistsellermodel',
            name='seller_name',
            field=models.TextField(max_length=64, verbose_name='除外セラー'),
        ),
        migrations.AlterField(
            model_name='blacklistwordmodel',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='exclusionasins',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='exclusionword',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='fetchurlmodel',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='pricesettingmodel',
            name='account_id',
            field=models.CharField(default='', max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='profitmodel',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='searchwordmodel',
            name='account_id',
            field=models.CharField(max_length=100, verbose_name='アカウントID'),
        ),
    ]
