# Generated by Django 3.1.6 on 2021-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0029_syuppincommonsettingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyuppinColumnConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, verbose_name='アカウントID')),
                ('syuppin_column_id', models.CharField(max_length=64, verbose_name='出品カラムID')),
                ('excel_column_id', models.CharField(max_length=64, verbose_name='ExcelカラムID')),
            ],
            options={
                'db_table': 't_syuppin_column_config',
            },
        ),
    ]
