# Generated by Django 3.1.6 on 2021-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0030_syuppincolumnconfigmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syuppincolumnconfigmodel',
            options={'verbose_name': '出品データカラム設定'},
        ),
        migrations.RemoveField(
            model_name='syuppincolumnconfigmodel',
            name='account_id',
        ),
    ]
