# Generated by Django 3.1.6 on 2021-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0031_auto_20210421_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syuppincolumnconfigmodel',
            name='syuppin_column_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='出品カラムID'),
        ),
    ]
