# Generated by Django 3.1.6 on 2021-04-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0032_auto_20210423_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syuppincolumnconfigmodel',
            name='syuppin_column_id',
            field=models.CharField(max_length=64, verbose_name='出品カラムID'),
        ),
    ]
