# Generated by Django 3.1.6 on 2021-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0033_auto_20210423_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchwordmodel',
            name='search_site',
            field=models.CharField(default='', max_length=10, verbose_name='検索サイト'),
        ),
    ]
