# Generated by Django 3.1.6 on 2021-05-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0034_searchwordmodel_search_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchwordmodel',
            name='search_site',
            field=models.CharField(max_length=10, verbose_name='検索サイト'),
        ),
    ]
