# Generated by Django 3.1.6 on 2021-05-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0035_auto_20210509_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplaceWordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=100, verbose_name='アカウントID')),
                ('base_word', models.CharField(max_length=128, verbose_name='対象ワード')),
                ('replace_word', models.CharField(max_length=128, null=True, verbose_name='置換ワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 't_replace_word',
            },
        ),
    ]
