# Generated by Django 3.1.6 on 2021-05-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0037_replacewordmodel_is_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitmodel',
            name='seq_no',
        ),
    ]
