# Generated by Django 3.1.6 on 2021-05-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0038_remove_profitmodel_seq_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchwordmodel',
            name='max_page_num',
            field=models.IntegerField(default=1, verbose_name='最大ページ数'),
        ),
    ]
