# Generated by Django 3.1.6 on 2021-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256, verbose_name='商品名')),
                ('item_id', models.CharField(default='', max_length=64, verbose_name='商品ID')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='商品説明')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
            ],
        ),
    ]
