# Generated by Django 2.2.5 on 2021-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyuppinDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, verbose_name='アカウントID')),
                ('yahoo_account_id', models.CharField(max_length=100, verbose_name='ヤフーID')),
                ('item_name', models.CharField(max_length=256, verbose_name='商品名')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='商品説明')),
                ('amazon_price', models.IntegerField(default=0, verbose_name='Amazon本体価格')),
                ('new_price', models.IntegerField(default=0, verbose_name='新品価格')),
                ('fba_price', models.IntegerField(default=0, verbose_name='FBA価格')),
                ('buybox_price', models.IntegerField(default=0, verbose_name='カート価格')),
                ('syuppin_price', models.IntegerField(default=0, verbose_name='出品価格')),
                ('sokketsu_price', models.IntegerField(default=0, verbose_name='即決価格')),
                ('thumbnail_path', models.CharField(default='', max_length=50, verbose_name='サムネイルPath')),
                ('image_path', models.CharField(default='', max_length=1024, verbose_name='画像Path')),
                ('category', models.CharField(default='', max_length=100, verbose_name='カテゴリー')),
                ('rank', models.IntegerField(default=0, verbose_name='ランキング')),
                ('asin', models.CharField(max_length=20, verbose_name='ASIN')),
                ('jan', models.CharField(max_length=100, verbose_name='JAN')),
                ('syuppin_stat', models.IntegerField(default=0, verbose_name='出品ステータス')),
                ('auction_id', models.CharField(max_length=20, null=True, verbose_name='オークションID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('syuppin_reserved_at', models.DateTimeField(null=True, verbose_name='出品予約日時')),
                ('syuppin_started_at', models.DateTimeField(null=True, verbose_name='出品開始日時')),
                ('syuppin_closed_at', models.DateTimeField(null=True, verbose_name='出品終了日時')),
            ],
            options={
                'db_table': 't_syuppin_data',
            },
        ),
    ]
