# Generated by Django 2.2.5 on 2021-03-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_asingroupmodel_started_at'),
        ('syuppin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppindatamodel',
            name='asin_group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='setting.AsinGroupModel'),
        ),
    ]
