# Generated by Django 2.2.5 on 2021-03-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0002_syuppindatamodel_asin_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syuppindatamodel',
            name='asin_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.AsinGroupModel'),
        ),
    ]
