# Generated by Django 3.1.6 on 2021-04-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0003_auto_20210302_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyuppinItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, verbose_name='アカウントID')),
                ('item_group_id', models.CharField(max_length=30, verbose_name='アイテムグループID')),
                ('item_name', models.CharField(max_length=256, verbose_name='商品名')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='商品説明')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('category', models.CharField(default='', max_length=50, verbose_name='カテゴリ')),
                ('brand', models.CharField(default='', max_length=50, verbose_name='ブランド')),
                ('shipping_payment', models.CharField(default='', max_length=20, verbose_name='配送料負担')),
                ('shipping_method', models.CharField(default='', max_length=20, verbose_name='配送料方法')),
                ('shipping_prefeture', models.CharField(default='', max_length=20, verbose_name='配送元')),
                ('shipping_leadtime', models.CharField(default='', max_length=20, verbose_name='配送までの期間')),
            ],
            options={
                'db_table': 't_syuppin_item',
            },
        ),
        migrations.DeleteModel(
            name='SyuppinDataModel',
        ),
    ]
