# Generated by Django 3.1.6 on 2021-04-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0004_auto_20210416_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=256, verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='item_group_id',
            field=models.CharField(max_length=32, verbose_name='アイテムグループID'),
        ),
    ]
