# Generated by Django 3.1.6 on 2021-04-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0006_syuppinitemmodel_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='item_id',
            field=models.CharField(default='', max_length=20, verbose_name='商品ID'),
        ),
    ]
