# Generated by Django 3.1.6 on 2021-04-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0009_syuppinitemmodel_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syuppinitemmodel',
            old_name='shipping_prefeture',
            new_name='shipping_prefecture',
        ),
    ]
