# Generated by Django 3.1.6 on 2021-04-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0010_auto_20210419_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url1',
            field=models.TextField(default='', null=True, verbose_name='画像1'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url10',
            field=models.TextField(default='', null=True, verbose_name='画像10'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url2',
            field=models.TextField(default='', null=True, verbose_name='画像2'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url3',
            field=models.TextField(default='', null=True, verbose_name='画像3'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url4',
            field=models.TextField(default='', null=True, verbose_name='画像4'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url5',
            field=models.TextField(default='', null=True, verbose_name='画像5'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url6',
            field=models.TextField(default='', null=True, verbose_name='画像6'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url7',
            field=models.TextField(default='', null=True, verbose_name='画像7'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url8',
            field=models.TextField(default='', null=True, verbose_name='画像8'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='image_url9',
            field=models.TextField(default='', null=True, verbose_name='画像9'),
        ),
    ]
