# Generated by Django 3.1.6 on 2021-04-19 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0011_auto_20210419_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_export_completed',
            field=models.BooleanField(default=False, verbose_name='出力完了フラグ'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='seller_name',
            field=models.CharField(default='', max_length=50, verbose_name='販売者名'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時'),
        ),
    ]
