# Generated by Django 3.1.6 on 2021-04-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0012_auto_20210419_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syuppinitemmodel',
            name='item_group_id',
        ),
    ]
