# Generated by Django 3.1.6 on 2021-04-23 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0014_auto_20210423_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='item_id',
            field=models.CharField(default='', max_length=20, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='item_sku',
            field=models.CharField(default=uuid.uuid4, max_length=20, verbose_name='商品SKU'),
        ),
    ]
