# Generated by Django 3.1.6 on 2021-04-30 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0015_auto_20210423_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='site',
            field=models.CharField(default='', max_length=20, verbose_name='取得元サイト'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='item_sku',
            field=models.CharField(default=uuid.uuid4, max_length=32, verbose_name='商品SKU'),
        ),
    ]
