# Generated by Django 3.1.6 on 2021-05-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0016_auto_20210430_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='amazon_price',
            field=models.IntegerField(default=0, verbose_name='販売価格'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='site',
            field=models.CharField(max_length=20, verbose_name='取得元サイト'),
        ),
    ]
