# Generated by Django 3.1.6 on 2021-05-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0017_auto_20210501_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='url',
            field=models.TextField(default='', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='syuppinitemmodel',
            name='item_id',
            field=models.CharField(default='', max_length=64, verbose_name='商品ID'),
        ),
    ]
