# Generated by Django 3.1.6 on 2021-05-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0018_auto_20210501_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image10_selected',
            field=models.BooleanField(default=False, verbose_name='画像10選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image1_selected',
            field=models.BooleanField(default=True, verbose_name='画像1選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image2_selected',
            field=models.BooleanField(default=False, verbose_name='画像2選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image3_selected',
            field=models.BooleanField(default=False, verbose_name='画像3選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image4_selected',
            field=models.BooleanField(default=False, verbose_name='画像4選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image5_selected',
            field=models.BooleanField(default=False, verbose_name='画像5選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image6_selected',
            field=models.BooleanField(default=False, verbose_name='画像6選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image7_selected',
            field=models.BooleanField(default=False, verbose_name='画像7選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image8_selected',
            field=models.BooleanField(default=False, verbose_name='画像8選択'),
        ),
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_image9_selected',
            field=models.BooleanField(default=False, verbose_name='画像9選択'),
        ),
    ]
