# Generated by Django 3.1.6 on 2021-05-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syuppin', '0020_auto_20210501_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='syuppinitemmodel',
            name='is_alert',
            field=models.BooleanField(default=False, verbose_name='アラート表示フラグ'),
        ),
    ]
