# Generated by Django 3.1.6 on 2021-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torihiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torihikimodel',
            name='rakusatsu_at',
            field=models.DateTimeField(null=True, verbose_name='落札日時'),
        ),
    ]
