# Generated by Django 3.1.6 on 2021-02-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torihiki', '0003_torihikimodel_eval_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torihikimodel',
            name='auction_id',
            field=models.CharField(max_length=20, verbose_name='オークションID'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='item_name',
            field=models.CharField(default='', max_length=256, verbose_name='商品名'),
        ),
    ]
