# Generated by Django 3.1.6 on 2021-02-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torihiki', '0004_auto_20210228_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torihikimodel',
            name='buied_price',
            field=models.IntegerField(default=0, null=True, verbose_name='落札価格'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='eval_flg',
            field=models.BooleanField(default=False, null=True, verbose_name='評価済フラグ'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='item_name',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='matome_flg',
            field=models.BooleanField(default=False, null=True, verbose_name='まとめフラグ'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='shipping_data',
            field=models.CharField(default=0, max_length=1024, null=True, verbose_name='落札価格'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='shipping_notice_flg',
            field=models.BooleanField(default=False, null=True, verbose_name='発送連絡済フラグ'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='torihiki_stat',
            field=models.IntegerField(default=0, null=True, verbose_name='取引ステータス'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
