# Generated by Django 3.1.6 on 2021-02-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torihiki', '0005_auto_20210228_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torihikimodel',
            old_name='eval_flg',
            new_name='eval_stat',
        ),
        migrations.RenameField(
            model_name='torihikimodel',
            old_name='shipping_notice_flg',
            new_name='shipping_notice_stat',
        ),
    ]
