# Generated by Django 3.1.6 on 2021-03-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torihiki', '0006_auto_20210228_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='torihikimodel',
            name='asin',
            field=models.CharField(default='', max_length=12, null=True, verbose_name='ASIN'),
        ),
    ]
