# Generated by Django 3.1.6 on 2021-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torihiki', '0007_torihikimodel_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='torihikimodel',
            name='amazon_price',
            field=models.IntegerField(default=0, null=True, verbose_name='Amazon価格'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='eval_stat',
            field=models.IntegerField(default=0, null=True, verbose_name='評価済フラグ'),
        ),
        migrations.AlterField(
            model_name='torihikimodel',
            name='shipping_notice_stat',
            field=models.IntegerField(default=0, null=True, verbose_name='発送連絡済フラグ'),
        ),
    ]
