# Generated by Django 3.1.6 on 2021-03-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torihiki', '0008_auto_20210301_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='torihikimodel',
            name='profit',
            field=models.IntegerField(default=0, null=True, verbose_name='利益'),
        ),
    ]
