from django.db import models
from django.http import request
from django.utils import timezone
from config.const import *

# 出品設定
class SyuppinCommonSettingModel(models.Model):
    account_id=models.CharField(max_length=100,default="",verbose_name='アカウントID',choices=())
    yahoo_account_id=models.CharField(max_length=100,default="",verbose_name="ヤフオクアカウントID") 
    # auction_mode=models.CharField(max_length=10,default="いいえ",verbose_name="オークション/フリマ選択",choices=SELECTION.AUCTION_MODE)
    # units=models.IntegerField(default=1,verbose_name='個数')
    # kaisai_kikan=models.IntegerField(default=1,verbose_name='開催期間',choices=SELECTION.KAISAI_KIKAN)
    # end_time=models.IntegerField(default=22,verbose_name='終了時間',choices=SELECTION.END_TIME)
    # shipping_address=models.CharField(max_length=10,default="海外",verbose_name="商品発送元の都道府県",choices=SELECTION.TODOUFUKEN)
    # souryou_futan=models.CharField(max_length=10,default="落札者",verbose_name="送料負担",choices=SELECTION.SOURYOU_FUTAN)
    # item_condition=models.CharField(max_length=10,default="未使用",verbose_name="商品の状態")
    # hyouka_seigen=models.CharField(max_length=10,default="いいえ",verbose_name="入札者評価制限",choices=SELECTION.YES_NO)
    # bad_hyouka_seigen=models.CharField(max_length=10,default="いいえ",verbose_name="悪い評価の割合での制限",choices=SELECTION.YES_NO)
    # nyuusatsusya_ninsyou_seigen=models.CharField(max_length=10,default="いいえ",verbose_name="入札者認証制限",choices=SELECTION.YES_NO)
    # auto_extention=models.CharField(max_length=10,default="はい",verbose_name="自動延長",choices=SELECTION.YES_NO)
    # fast_end=models.CharField(max_length=10,default="はい",verbose_name="早期終了",choices=SELECTION.YES_NO)
    # auto_saisyuppin=models.IntegerField(default=3,verbose_name="自動再出品",choices=SELECTION.AUTO_SAI_SYUPPIN)
    # shipping_date=models.CharField(max_length=10,default="1～2日",verbose_name="発送までの日数",choices=SELECTION.SHIPPING_DATE)
    # other_shipping_method=models.CharField(max_length=20,default="委託配送会社して一律料金",verbose_name="配送方法１")
    # other_shipping_price=models.IntegerField(default=0,verbose_name="配送方法１の一律価格")
    # description_template=models.TextField(default="<CENTER>$$description$$</CENTER>",verbose_name="説明文テンプレート(　$$description$$　を商品説明を入れたい箇所に入力してください)")
    # syuppin_sleep_sec = models.IntegerField("出品毎の待ち時間(秒)", default=5)

    #今回使用するテーブル類(必須)
    brand_name=models.CharField(max_length=50,default="",verbose_name='ブランド名')
    #コンディション状態の文字列のマックスの設定が必要
    condition_note=models.CharField(max_length=333,default="",verbose_name='商品のコンディション説明')
    condition_type=models.CharField(max_length=30,default="未使用",verbose_name='商品のコンディション',choices=SELECTION.CONDITION)
    feed_product_type=models.CharField(max_length=30,default="",verbose_name='商品タイプ',choices=SELECTION.FEED)
    fulfillment_latency=models.IntegerField(max_length=10,default=0,verbose_name="出荷作業日数")
    is_adult_product=models.CharField(max_length=10,default="FALSE",verbose_name="アダルト商品",choices=SELECTION.TRUE_FALSE)
    manufacturer=models.CharField(max_length=50,default="",verbose_name="メーカー名")
    model=models.CharField(max_length=50,default="NON",verbose_name='型番')
    part_number=models.CharField(max_length=40,default="NON",verbose_name='メーカ型番')
    quantity=models.IntegerField(default=1,verbose_name='数量')
    recommended_browse_nodes=models.CharField(max_length=30,default="",verbose_name="推奨ブラウズノード",choices=SELECTION.BRAWSE)
    standard_price_points=models.IntegerField(default=0,verbose_name='ポイント')
    update_delete=models.CharField(max_length=30,default="",verbose_name="アップデート・削除",choices=SELECTION.UPDATEORDELETE)
    #追加テーブル
    item_sku=models.CharField(max_length=30,default="",verbose_name="出品者SKU",null=True)
    item_name=models.CharField(max_length=50,default="",verbose_name="商品名",null=True)
    external_product_id=models.CharField(max_length=16,default="",verbose_name="商品コード(JANコード)",null=True)
    external_product_id_type=models.CharField(max_length=16,default="",verbose_name="商品コードのタイプ",null=True)
    standard_price=models.IntegerField(max_length=18,default=0,verbose_name="商品の販売価格",null=True)
    main_image_url=models.CharField(max_length=500,default="",verbose_name="商品メイン画像URL",null=True)
    other_image_url1=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL1",null=True)
    other_image_url2=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL2",null=True)
    other_image_url3=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL3",null=True)
    other_image_url4=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL4",null=True)
    other_image_url5=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL5",null=True)
    other_image_url6=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL6",null=True)
    other_image_url7=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL7",null=True)
    other_image_url8=models.CharField(max_length=500,default="",verbose_name="商品サブ画像URL8",null=True)
    swatch_image_url=models.CharField(max_length=500,default="",verbose_name="カラーサンプル画像",null=True)
    parent_child=models.CharField(max_length=10,default="",verbose_name="親子関係の指定",null=True,choices=SELECTION.PARENT)
    variation_theme=models.CharField(max_length=50,default="",verbose_name="バリエーションテーマ",null=True,choices=SELECTION.VARIATION)
    parent_sku=models.CharField(max_length=40,default="",verbose_name="親商品のSKU（商品管理番号）",null=True)
    relationship_type=models.CharField(max_length=10,default="Variation",verbose_name="親子関係のタイプ",null=True)
    product_description=models.CharField(max_length=666,default="",verbose_name="商品説明",null=True)
    target_gender=models.CharField(max_length=10,default="",verbose_name="対象性別",null=True,choices=SELECTION.GENDER)
    care_instructions1=models.CharField(max_length=166,default="",verbose_name="お取り扱い上の注意",null=True)
    care_instructions2=models.CharField(max_length=166,default="",verbose_name="お取り扱い上の注意",null=True)
    care_instructions3=models.CharField(max_length=166,default="",verbose_name="お取り扱い上の注意",null=True)
    language_value=models.CharField(max_length=20,default="",verbose_name="対応言語",null=True,choices=SELECTION.LANGUAGE)
    edition=models.CharField(max_length=20,default="",verbose_name="版",null=True)
    bullet_point1=models.CharField(max_length=166,default="",verbose_name="商品の仕様",null=True)
    bullet_point2=models.CharField(max_length=166,default="",verbose_name="商品の仕様",null=True)
    bullet_point3=models.CharField(max_length=166,default="",verbose_name="商品の仕様",null=True)
    bullet_point4=models.CharField(max_length=166,default="",verbose_name="商品の仕様",null=True)
    bullet_point5=models.CharField(max_length=166,default="",verbose_name="商品の仕様",null=True)
    generic_keywords=models.CharField(max_length=50,default="",verbose_name="検索キーワード",null=True)
    mfg_minimum_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="メーカー推奨最少年齢の単位",null=True,choices=SELECTION.MINIMUMAGE)
    mfg_maximum_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="メーカー推奨最少年齢の単位",null=True,choices=SELECTION.MINIMUMAGE)
    assembly_instructions=models.CharField(max_length=500,default="",verbose_name="組み立て方法",null=True)
    is_assembly_required=models.CharField(max_length=10,default="",verbose_name="要組み立て",null=True,choices=SELECTION.TRUE_FALSE)
    assembly_time_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="組み立て時間の単位 - [ hobbies ]",null=True,choices=SELECTION.MEASURE)
    assembly_time=models.IntegerField(max_length=10,default=0,verbose_name="組み立て時間",null=True)
    folded_size=models.CharField(max_length=166,default="",verbose_name="折りたたみ時のサイズ",null=True)
    material_type=models.CharField(max_length=20,default="",verbose_name="素材の種類",null=True,choices=SELECTION.MATERIAL)
    special_features1=models.CharField(max_length=166,default="",verbose_name="機能性",null=True)
    special_features2=models.CharField(max_length=166,default="",verbose_name="機能性",null=True)
    special_features3=models.CharField(max_length=166,default="",verbose_name="機能性",null=True)
    special_features4=models.CharField(max_length=166,default="",verbose_name="機能性",null=True)
    special_features5=models.CharField(max_length=166,default="",verbose_name="機能性",null=True)
    size_name=models.CharField(max_length=50,default="",verbose_name="サイズ",null=True)
    color_name=models.CharField(max_length=50,default="",verbose_name="カラー",null=True)
    color_map=models.CharField(max_length=20,default="",verbose_name="カラーマップ",null=True,choices=SELECTION.COLORMAP)
    number_of_pieces=models.IntegerField(max_length=10,default=0,verbose_name="商品の個数（ピース数）",null=True)
    engine_type=models.CharField(max_length=10,default="",verbose_name="エンジンタイプ",null=True,choices=SELECTION.ENGINE)
    recommended_uses_for_product=models.CharField(max_length=10,default="",verbose_name="推奨使用用途",null=True,choices=SELECTION.RECPRODUCT)
    collection_name=models.CharField(max_length=32,default="",verbose_name="コレクション名",null=True)
    genre=models.CharField(max_length=50,default="",verbose_name="ジャンル",null=True)
    battery_description=models.CharField(max_length=32,default="",verbose_name="電池の説明",null=True)
    lithium_battery_voltage=models.CharField(max_length=10,default="",verbose_name="リチウム電池エネルギー含有量",null=True)
    catalog_number=models.CharField(max_length=40,default="",verbose_name='出品者カタログ番号',null=True)
    platinum_keywords1=models.CharField(max_length=50,default="",verbose_name="プラチナキーワード",null=True)
    platinum_keywords2=models.CharField(max_length=50,default="",verbose_name="プラチナキーワード",null=True)
    platinum_keywords3=models.CharField(max_length=50,default="",verbose_name="プラチナキーワード",null=True)
    platinum_keywords4=models.CharField(max_length=50,default="",verbose_name="プラチナキーワード",null=True)
    platinum_keywords5=models.CharField(max_length=50,default="",verbose_name="プラチナキーワード",null=True)
    #推奨値なし
    style_name=models.CharField(max_length=50,default="",verbose_name="スタイル名",null=True)
    lithium_battery_voltage_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="リチウム電池の電圧の測定単位",null=True,choices=SELECTION.LITHIUM)
    target_audience_keywords1=models.CharField(max_length=50,default="",verbose_name="ターゲットユーザーのキーワード",null=True)
    target_audience_keywords2=models.CharField(max_length=50,default="",verbose_name="ターゲットユーザーのキーワード",null=True)
    target_audience_keywords3=models.CharField(max_length=50,default="",verbose_name="ターゲットユーザーのキーワード",null=True)
    target_audience_keywords4=models.CharField(max_length=50,default="",verbose_name="ターゲットユーザーのキーワード",null=True)
    target_audience_keywords5=models.CharField(max_length=50,default="",verbose_name="ターゲットユーザーのキーワード",null=True)
    shaft_style_type=models.CharField(max_length=50,default="",verbose_name="shaft_style_type",null=True)
    controller_type=models.CharField(max_length=20,default="",verbose_name="コントローラタイプ",null=True,choices=SELECTION.CONTROLLER)
    mfg_minimum=models.IntegerField(max_length=20,default=0,verbose_name="メーカー推奨最少年齢",null=True)
    mfg_maximum=models.IntegerField(max_length=20,default=0,verbose_name="メーカー推奨最高年齢",null=True)
    subject_character=models.CharField(max_length=50,default="",verbose_name="キャラクター",null=True)
    material_composition=models.CharField(max_length=333,default="",verbose_name="素材構成",null=True)
    scale_name=models.CharField(max_length=10,default="",verbose_name="スケール名",null=True,choices=SELECTION.SCALE)
    rail_gauge=models.CharField(max_length=10,default="",verbose_name="レールの規格",null=True,choices=SELECTION.RAIL)
    remote_control_technology=models.CharField(max_length=10,default="",verbose_name="有線or無線",null=True,choices=SELECTION.REMOTE)
    frequency_bands_supported=models.CharField(max_length=166,default="",verbose_name="サポート周波数帯域",null=True)
    educational_objective=models.CharField(max_length=166,default="",verbose_name="教育目標",null=True)
    website_shipping_weight=models.FloatField(max_length=20,default=0,verbose_name="配送重量",null=True)
    website_shipping_weight_unit_of_measure=models.CharField(max_length=20,default="",verbose_name="発送重量の単位",null=True,choices=SELECTION.SHIPPING)
    minimum_weight_recommendation=models.FloatField(max_length=20,default=0,verbose_name="メーカー推奨最低重量(日本では使用不可)",null=True)
    minimum_weight_recommendation_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="メーカー推奨最少体重の単位(日本では使用不可)",null=True,choices=SELECTION.MINWEIGHT)
    maximum_weight_recommendation=models.FloatField(max_length=20,default=0,verbose_name="メーカー推奨最大重量(日本では使用不可)",null=True)
    maximum_weight_recommendation_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="メーカー推奨最大体重の単位(日本では使用不可)",null=True,choices=SELECTION.MAXWEIGHT)
    minimum_height_recommendation=models.FloatField(max_length=20,default=0,verbose_name="メーカー推奨最低身長(日本では使用不可)",null=True)
    minimum_height_recommendation_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="推奨最低身長の単位",null=True,choices=SELECTION.MINHEIGHT)
    maximum_height_recommendation=models.FloatField(max_length=20,default=0,verbose_name="メーカー推奨最大身長(日本で使用不可)",null=True)
    maximum_height_recommendation_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="推奨最高身長の単位(日本で使用不可)",null=True,choices=SELECTION.MAXHEIGHT)
    size_map=models.CharField(max_length=10,default="",verbose_name="サイズマップ",null=True,choices=SELECTION.SIZEMAP)
    handle_height=models.FloatField(max_length=10,default=0,verbose_name="ハンドルの高さ",null=True)
    handle_height_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="ハンドルの高さの単位",null=True,choices=SELECTION.HANDLE)
    seat_width=models.FloatField(max_length=10,default=0,verbose_name="シートの幅",null=True)
    seat_width_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="座面（椅子）の幅の単位",null=True,choices=SELECTION.SEAT)
    item_height=models.FloatField(max_length=10,default=0,verbose_name="商品の高さ",null=True)
    item_length=models.FloatField(max_length=10,default=0,verbose_name="商品の長さ",null=True)
    item_width=models.FloatField(max_length=10,default=0,verbose_name="商品の幅",null=True)
    item_display_weight=models.FloatField(max_length=10,default=0,verbose_name="商品の重量（パッケージを含まない）(日本では使用不可)",null=True)
    item_display_weight_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="商品の重量の単位(日本では使用不可)",null=True,choices=SELECTION.DISWEIGHT)
    item_display_length=models.FloatField(max_length=10,default=0,verbose_name="商品の長さ（パッケージを含まない）(日本では使用不可)",null=True)
    item_display_length_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="商品の長さの単位(日本では使用不可)",null=True,choices=SELECTION.DISLENGTH)
    item_dimensions_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="商品の寸法の単位",null=True,choices=SELECTION.ITEMDIMENTION)
    fulfillment_center_id=models.CharField(max_length=10,default="",verbose_name="フルフィルメントセンターID",null=True,choices=SELECTION.FULFILID)
    package_length=models.FloatField(max_length=10,default=0,verbose_name="商品パッケージの長さ",null=True)
    package_width=models.FloatField(max_length=10,default=0,verbose_name="商品パッケージの幅",null=True)
    package_height=models.FloatField(max_length=10,default=0,verbose_name="商品パッケージの高さ",null=True)
    package_weight=models.FloatField(max_length=10,default=0,verbose_name="商品パッケージの重量",null=True)
    package_weight_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="商品パッケージの重量の単位",null=True,choices=SELECTION.PACKWEIGHT)
    package_dimensions_unit_of_measure=models.CharField(max_length=10,default="",verbose_name="商品パッケージの寸法の単位",null=True,choices=SELECTION.PACKDIMENTION)
    legal_disclaimer_description=models.CharField(max_length=333,default="",verbose_name="法規上の免責条項",null=True)
    safety_warning=models.CharField(max_length=500,default="",verbose_name="安全性の注意点",null=True)
    warranty_description=models.CharField(max_length=500,default="",verbose_name="メーカー保証の説明",null=True)
    country_string=models.CharField(max_length=50,default="",verbose_name="製造国/地域",null=True,choices=SELECTION.COUNTORY)
    country_of_origin=models.CharField(max_length=50,default="",verbose_name="原産国/地域",null=True)
    specific_uses_for_product=models.CharField(max_length=50,default="",verbose_name="特徴・用途",null=True)
    are_batteries_included=models.CharField(max_length=50,default="",verbose_name="電池付属",null=True)
    batteries_required=models.CharField(max_length=5,default="",verbose_name="この商品は電池本体ですか？または電池を使用した商品ですか？",null=True,choices=SELECTION.YES_NO)
    battery_type1=models.CharField(max_length=20,default="",verbose_name="電池付属",null=True,choices=SELECTION.BATTERY)
    battery_type2=models.CharField(max_length=20,default="",verbose_name="電池付属",null=True,choices=SELECTION.BATTERY)
    battery_type3=models.CharField(max_length=20,default="",verbose_name="電池付属",null=True,choices=SELECTION.BATTERY)
    number_of_batteries1=models.IntegerField(max_length=10,default=0,verbose_name="電池の数",null=True)
    number_of_batteries2=models.IntegerField(max_length=10,default=0,verbose_name="電池の数",null=True)
    number_of_batteries3=models.IntegerField(max_length=10,default=0,verbose_name="電池の数",null=True)
    lithium_battery_energy_content=models.IntegerField(max_length=10,default=0,verbose_name="電池当たりのワット時",null=True)
    number_of_lithium_ion_cells=models.IntegerField(max_length=10,default=0,verbose_name="リチウムイオン電池単数",null=True)
    number_of_lithium_metal_cells=models.IntegerField(max_length=10,default=0,verbose_name="リチウムメタル電池単数",null=True)
    lithium_battery_weight=models.IntegerField(max_length=10,default=0,verbose_name="リチウム含有量(グラム)",null=True)
    lithium_battery_packaging=models.CharField(max_length=20,default="",verbose_name="リチウム電池パッケージ",null=True,choices=SELECTION.LITHPACK)
    item_weight=models.FloatField(max_length=10,default=0,verbose_name="商品の重量",null=True)
    item_weight_unit_of_measure=models.CharField(max_length=20,default="",verbose_name="商品の重量の単位",null=True,choices=SELECTION.MINWEIGHT)
    battery_cell_composition=models.CharField(max_length=30,default="",verbose_name="電池の組成",null=True,choices=SELECTION.COMP)
    battery_weight=models.IntegerField(max_length=10,default=0,verbose_name="電池の重量(グラム)",null=True)
    battery_weight_unit_of_measure=models.CharField(max_length=20,default="",verbose_name="電池の重量の測定単位",null=True,choices=SELECTION.MINWEIGHT)
    lithium_battery_energy_content_unit_of_measure=models.CharField(max_length=20,default="",verbose_name="リチウム電池のエネルギー量測定単位",null=True,choices=SELECTION.ENERGY)
    lithium_battery_weight_unit_of_measure=models.CharField(max_length=20,default="",verbose_name="リチウム電池の重量の測定単位",null=True,choices=SELECTION.MINWEIGHT)
    supplier_declared_dg_hz_regulation1=models.CharField(max_length=20,default="",verbose_name="適用される危険物関連法令",null=True,choices=SELECTION.DGHZ)
    supplier_declared_dg_hz_regulation2=models.CharField(max_length=20,default="",verbose_name="適用される危険物関連法令",null=True,choices=SELECTION.DGHZ)
    supplier_declared_dg_hz_regulation3=models.CharField(max_length=20,default="",verbose_name="適用される危険物関連法令",null=True,choices=SELECTION.DGHZ)
    supplier_declared_dg_hz_regulation4=models.CharField(max_length=20,default="",verbose_name="適用される危険物関連法令",null=True,choices=SELECTION.DGHZ)
    supplier_declared_dg_hz_regulation5=models.CharField(max_length=20,default="",verbose_name="適用される危険物関連法令",null=True,choices=SELECTION.DGHZ)
    hazmat_united_nations_regulatory_id=models.CharField(max_length=50,default="",verbose_name="国連(UN)番号",null=True)
    safety_data_sheet_url=models.CharField(max_length=300,default="",verbose_name="安全データシート(SDS) URL",null=True)
    item_volume=models.FloatField(max_length=10,default=0,verbose_name="商品の体積",null=True)
    item_volume_unit_of_measure=models.CharField(max_length=20,default="",verbose_name="商品の容量の単位",null=True,choices=SELECTION.VOLUME)
    flash_point=models.IntegerField(max_length=10,default=0,verbose_name="引火点(°C)",null=True)
    ghs_classification_class1=models.CharField(max_length=20,default="",verbose_name="商品の容量の単位",null=True,choices=SELECTION.GHS)
    ghs_classification_class2=models.CharField(max_length=20,default="",verbose_name="商品の容量の単位",null=True,choices=SELECTION.GHS)
    ghs_classification_class3=models.CharField(max_length=20,default="",verbose_name="商品の容量の単位",null=True,choices=SELECTION.GHS)
    product_site_launch_date=models.DateField(null=True,verbose_name="商品の公開日")
    merchant_release_date=models.DateField(null=True,verbose_name="予約商品の販売開始日")
    restock_date=models.DateField(null=True,verbose_name="商品の入荷予定日")
    optional_payment_type_exclusion=models.CharField(max_length=20,default="",verbose_name="使用しない支払い方法",null=True,choices=SELECTION.EXCLUSION)
    delivery_schedule_group_id=models.CharField(max_length=50,default="",verbose_name="配送日時指定SKUリスト",null=True)
    sale_price=models.IntegerField(max_length=18,default=0,verbose_name="セール価格",null=True)
    sale_from_date=models.DateField(null=True,verbose_name="セール開始日")
    sale_end_date=models.DateField(null=True,verbose_name="セール終了日")
    standard_price_points=models.IntegerField(max_length=10,default=0,verbose_name="セール価格",null=True)
    sale_price_points=models.IntegerField(max_length=10,default=0,verbose_name="セール時ポイント",null=True)
    item_package_quantity=models.IntegerField(max_length=10,default=0,verbose_name="パッケージ商品数",null=True)
    list_price=models.IntegerField(max_length=10,default=0,verbose_name="メーカー希望価格",null=True)
    number_of_items=models.IntegerField(max_length=10,default=0,verbose_name="付属品総数",null=True)
    offering_can_be_giftwrapped=models.CharField(max_length=50,default="",verbose_name="ギフト包装",null=True)
    offering_can_be_gift_messaged=models.CharField(max_length=50,default="",verbose_name="ギフトメッセージ",null=True)
    max_order_quantity=models.IntegerField(max_length=5,default=0,verbose_name="最大注文個数",null=True)
    is_discontinued_by_manufacturer=models.CharField(max_length=10,default="",verbose_name="メーカー製造中止",null=True,choices=SELECTION.YES_NO)
    offering_end_date=models.DateField(null=True,verbose_name="セール終了日")
    product_tax_code=models.CharField(max_length=10,default="",verbose_name="商品タックスコード",null=True,choices=SELECTION.TAXCODE)
    merchant_shipping_group_name=models.CharField(max_length=10,default="",verbose_name="配送パターン",null=True,choices=SELECTION.MERCHANT)
    is_expiration_dated_product=models.CharField(max_length=10,default="",verbose_name="賞味期限管理商品",null=True,choices=SELECTION.TRUE_FALSE)
    distribution_designation=models.CharField(max_length=10,default="",verbose_name="販売形態(並行輸入品)",null=True,choices=SELECTION.DISTRI)
    offering_start_date=models.DateField(null=True,verbose_name="販売開始日")
    business_price=models.IntegerField(max_length=18,default=0,verbose_name="法人価格",null=True)
    quantity_price_type=models.CharField(max_length=10,default="",verbose_name="数量割引のタイプ",null=True,choices=SELECTION.QUANTPRICE)
    quantity_lower_bound1=models.IntegerField(max_length=18,default=0,verbose_name="数量の下限1",null=True)
    quantity_price1=models.CharField(max_length=10,default="",verbose_name="数量割引1",null=True)
    quantity_lower_bound2=models.IntegerField(max_length=18,default=0,verbose_name="数量の下限2",null=True)
    quantity_price2=models.CharField(max_length=10,default="",verbose_name="数量割引2",null=True)
    quantity_lower_bound3=models.IntegerField(max_length=18,default=0,verbose_name="数量の下限3",null=True)
    quantity_price3=models.CharField(max_length=10,default="",verbose_name="数量割引3",null=True)
    quantity_lower_bound4=models.IntegerField(max_length=18,default=0,verbose_name="数量の下限4",null=True)
    quantity_price4=models.CharField(max_length=10,default="",verbose_name="数量割引4",null=True)
    quantity_lower_bound5=models.IntegerField(max_length=18,default=0,verbose_name="数量の下限5",null=True)
    quantity_price5=models.CharField(max_length=10,default="",verbose_name="数量割引5",null=True)
    progressive_discount_type=models.CharField(max_length=10,default="",verbose_name="累積購入割引のタイプ",null=True,choices=SELECTION.QUANTPRICE)
    progressive_discount_lower_bound1=models.IntegerField(max_length=18,default=0,verbose_name="累積購入割引の下限値1",null=True)
    progressive_discount_value1=models.IntegerField(max_length=18,default=0,verbose_name="累積購入割引価格1",null=True)
    progressive_discount_lower_bound2=models.IntegerField(max_length=18,default=0,verbose_name="累積購入割引の下限値2",null=True)
    progressive_discount_value2=models.IntegerField(max_length=18,default=0,verbose_name="累積購入割引価格2",null=True)
    progressive_discount_lower_bound3=models.IntegerField(max_length=18,default=0,verbose_name="累積購入割引の下限値3",null=True)
    progressive_discount_value3=models.IntegerField(max_length=18,default=0,verbose_name="累積購入割引価格3",null=True)
    pricing_action=models.CharField(max_length=10,default="",verbose_name="価格設定操作",null=True,choices=SELECTION.ACTION)
    
    class Meta:
        db_table='t_syuppin_common_setting'
    